window.DATOS_BATERIA = {
    categorias: ["J'", "Je", "Tu", "Il", "Nous", "Vous", "Ils", "J´ / Il", "Je / Il", "J´ / Tu", "Je / Il"], 
    palabras: [
        { texto: "associe", cat: 7 },
        { texto: "associe", cat: 7 },
        { texto: "associent", cat: 6 },
        { texto: "associes", cat: 2 },
        { texto: "associez", cat: 5 },
        { texto: "associons", cat: 4 },
        { texto: "corrige", cat: 8 },
        { texto: "corrige", cat: 8 },
        { texto: "corrigent", cat: 6 },
        { texto: "corrigeons", cat: 4 },
        { texto: "corriges", cat: 2 },
        { texto: "corrigez", cat: 5 },
        { texto: "écris", cat: 9 },
        { texto: "écris", cat: 9 },
        { texto: "écrit", cat: 3 },
        { texto: "écrivent", cat: 6 },
        { texto: "écrivez", cat: 5 },
        { texto: "écrivons", cat: 4 },
        { texto: "lis", cat: 10 },
        { texto: "lis", cat: 10 },
        { texto: "lisent", cat: 6 },
        { texto: "lisez", cat: 5 },
        { texto: "lisons", cat: 4 },
        { texto: "lit", cat: 3 },
        { texto: "m'assieds", cat: 1 },
        { texto: "me tais", cat: 1 },
        { texto: "nous asseyons", cat: 4 },
        { texto: "nous taisons", cat: 4 },
        { texto: "s'asseyent", cat: 6 },
        { texto: "s'assied", cat: 3 },
        { texto: "se taisent", cat: 6 },
        { texto: "se tait", cat: 3 },
        { texto: "sors", cat: 10 },
        { texto: "sors", cat: 10 },
        { texto: "sort", cat: 3 },
        { texto: "sortent", cat: 6 },
        { texto: "sortez", cat: 5 },
        { texto: "sortons", cat: 4 },
        { texto: "t'assieds", cat: 2 },
        { texto: "te tais", cat: 2 },
        { texto: "vous asseyez", cat: 5 },
        { texto: "vous taisez", cat: 5 }



]
};
