// Estructura de batería para el ejercicio de clasificación (Drag & Drop)



window.DATOS_BATERIA= {
    categorias: ["C", "G", "GÜ", "J", "K", "QU", "R", "RR", "Z", "GU"],
    palabras: [

        { texto: "má.....ina", cat: 5 },
        { texto: "alcorno.....e", cat: 5 },
        { texto: ".....ostoso", cat: 0 },
        { texto: "es.....ema", cat: 5 },
        { texto: ".....aramelo", cat: 0 },
        { texto: "ar.....o", cat: 0 },
        { texto: "cro.....eta", cat: 5 },
        { texto: ".....ara.....ol", cat: 0 },
        { texto: "bás.....ula", cat: 0 },
        { texto: "bo.....adillo", cat: 0 },
        { texto: ".....ucharilla", cat: 0 },
        { texto: "eus.....era", cat: 4 },
        { texto: "ros.....illa", cat: 5 },
        { texto: "es.....udo", cat: 0 },
        { texto: "mas.....ota", cat: 0 },
        { texto: "mo.....eta", cat: 5 },
        { texto: ".....ebolla", cat: 0 },
        { texto: "chori.....o", cat: 8 },
        { texto: "eri.....o", cat: 8 },
        { texto: "a.....afata", cat: 8 },
        { texto: ".....isne", cat: 0 },
        { texto: "a.....úcar", cat: 8 },
        { texto: "Mar.....elo", cat: 0 },
        { texto: "peda.....o", cat: 8 },
        { texto: "á.....ido", cat: 0 },
        { texto: "pe.....uña", cat: 8 },
        { texto: ".....iruela", cat: 0 },
        { texto: "bra.....alete", cat: 8 },
        { texto: "se.....undo", cat: 1 },
        { texto: ".....onzalo", cat: 1 },
        { texto: "re.....adera", cat: 1 },
        { texto: "a.....uado", cat: 1 },
        { texto: "espa.....etis", cat: 9 },
        { texto: ".....usano", cat: 1 },
        { texto: "pira.....ista", cat: 2 },
        { texto: "un.....ento", cat: 2 },
        { texto: "pin.....ino", cat: 2 },
        { texto: ".....abardina", cat: 1 },
        { texto: "bilin.....e", cat: 2 },
        { texto: ".....inda", cat: 9 },
        { texto: ".....irnalda", cat: 9 },
        { texto: "man.....era", cat: 9 },
        { texto: "ci.....eña", cat: 2 },
        { texto: "anti.....uo", cat: 1 },
        { texto: ".....inete", cat: 3 },
        { texto: "ti.....eras", cat: 3 },
        { texto: ".....irasol", cat: 1 },
        { texto: "patina.....e", cat: 3 },
        { texto: "in.....erir", cat: 1 },
        { texto: "bru.....a", cat: 3 },
        { texto: "mu.....er", cat: 3 },
        { texto: "con.....elar", cat: 1 },
        { texto: "escaraba.....o", cat: 3 },
        { texto: "Án.....el", cat: 1 },
        { texto: "tra.....ín", cat: 3 },
        { texto: "me.....illón", cat: 3 },
        { texto: "ore.....a", cat: 3 },
        { texto: ".....igante", cat: 1 },
        { texto: ".....ugador", cat: 3 },
        { texto: "co.....ín", cat: 3 },
        { texto: ".....ápido", cat: 6 },
        { texto: "altu.....a", cat: 6 },
        { texto: "aca.....ear", cat: 7 },
        { texto: "son.....isa", cat: 6 },
        { texto: "is.....aelí", cat: 6 },
        { texto: "ce.....adura", cat: 7 },
        { texto: ".....esolver", cat: 6 },
        { texto: "sale.....o", cat: 6 },
        { texto: "bande.....a", cat: 6 },
        { texto: ".....egalo", cat: 6 },
        { texto: "ba.....io", cat: 7 },
        { texto: "en.....ollar", cat: 7 },
        { texto: "sie.....a", cat: 7 },
        { texto: "Ampa.....o", cat: 6 },
        { texto: ".....eceta", cat: 6 },
        { texto: "bate…..ía", cat: 6 }


    ]
};
