var DATOS_BATERIA = [
 { id: 1, enunciado: "Hola", opciones: ["Salut", "Ce n'est rien", "Bonsoir", "Ciao"], correcta:  0, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 2, enunciado: "Hola", opciones: ["Bonjour", "Bonne nuit", "Ce n'est rien", "Merci"], correcta:  0, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 3, enunciado: "Buenos días", opciones: ["Bonjour", "Bonne nuit", "Bonsoir", "Ce n'est rien"], correcta:  0, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 4, enunciado: "Buenas tardes", opciones: ["Bonsoir", "Bonjour", "Merci beaucoup", "Salut"], correcta:  0, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 5, enunciado: "Buenas noches", opciones: ["Bonjour", "Ciao", "Bonne nuit", "Bonne soirée"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 6, enunciado: "Sí", opciones: ["Bonsoir", "Bonjour", "Oui", "Ciao"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 7, enunciado: "No", opciones: ["Bonne nuit", "Bonsoir", "Non", "Oui"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 8, enunciado: "Por favor", opciones: ["Oui", "Bonne nuit", "S'il vous plaît", "Non"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 9, enunciado: "Gracias", opciones: ["Non", "Oui", "Merci", "S'il vous plaît"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 10, enunciado: "Muchas gracias", opciones: ["S'il vous plaît", "Non", "Merci beaucoup", "Merci"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 11, enunciado: "De nada", opciones: ["Merci", "S'il vous plaît", "De rien", "Merci beaucoup"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 12, enunciado: "Señor", opciones: ["Merci beaucoup", "Merci", "Monsieur", "De rien"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 13, enunciado: "Señores", opciones: ["De rien", "Merci beaucoup", "Messieurs", "Monsieur"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 14, enunciado: "Señora", opciones: ["Monsieur", "De rien", "Madame", "Messieurs"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 15, enunciado: "Señoras", opciones: ["Messieurs", "Monsieur", "Mesdames", "Madame"], correcta:  2, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 16, enunciado: "Señorita", opciones: ["Mesdames", "Madame", "Messieurs", "Mademoiselle"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 17, enunciado: "Señoritas", opciones: ["Mademoiselle", "Mesdames", "Madame", "Mesdemoiselles"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 18, enunciado: "Adiós", opciones: ["Mesdemoiselles", "Mademoiselle", "Mesdames", "Au revoir"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 19, enunciado: "Adiós", opciones: ["À tout à l'heure", "Bonne nuit", "Mademoiselle", "Salut"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 20, enunciado: "Adiós", opciones: ["Oui", "Bonne nuit", "Bonsoir", "Ciao"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 21, enunciado: "Hasta pronto", opciones: ["Ciao", "Salut", "Au revoir", "À bientôt"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 22, enunciado: "Hasta luego", opciones: ["À bientôt", "Ciao", "Salut", "À plus tard"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 23, enunciado: "Hasta luego", opciones: ["À plus tard", "À bientôt", "Ciao", "À tout à l'heure"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 24, enunciado: "Hasta la próxima", opciones: ["À tout à l'heure", "À plus tard", "À bientôt", "À la prochaine"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 25, enunciado: "Hasta mañana", opciones: ["À la prochaine", "À tout à l'heure", "À plus tard", "À demain"], correcta:  3, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 26, enunciado: "Bienvenido", opciones: ["À tout à l'heure", "Bienvenu", "À demain", "À la prochaine"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 27, enunciado: "Bienvenida", opciones: ["Bienvenu", "Bienvenue", "Bienvenu", "À demain"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 28, enunciado: "Encantado", opciones: ["À demain", "Enchanté", "Bienvenue", "Bienvenu"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 29, enunciado: "Encantada", opciones: ["Bienvenu", "Enchantée", "Enchanté", "Bienvenue"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 30, enunciado: "Que pases un buen día", opciones: ["Bienvenue", "Bonne journée", "Enchantée", "Bienvenu"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 31, enunciado: "Que pases una buena noche", opciones: ["Enchanté", "Bonne soirée", "Bonne journée", "Enchantée"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 32, enunciado: "Perdón", opciones: ["Enchantée", "Pardon", "Bonne soirée", "Bonne journée"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 33, enunciado: "Lo siento", opciones: ["Bonne journée", "Désolé", "Pardon", "Bonne soirée"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 34, enunciado: "Lo siento", opciones: ["Bonne soirée", "Je suis désolé", "Bienvenue", "Pardon"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 35, enunciado: "Perdóname", opciones: ["Pardon", "Excuse-moi", "Je suis désolé", "Désolé"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 36, enunciado: "Perdóneme", opciones: ["Désolé", "Excusez-moi", "Excuse-moi", "Je suis désolé"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 37, enunciado: "No hay problema", opciones: ["Je suis désolé", "Il n'y a pas de problème", "Excusez-moi", "Excuse-moi"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 38, enunciado: "No es nada", opciones: ["Excuse-moi", "Ce n'est rien", "Il n'y a pas de problème", "Excusez-moi"], correcta:  1, observaciones: "La cifra de las centenas es la tercera de la parte entera contando desde la derecha." },
 { id: 39, enunciado: "La palabra Observa el número 2817. Indica cuál es la cifra de las DECENAS: es un adverbio de: ", opciones: ["9", "6", "1", "7"], correcta:  2, observaciones: "La cifra de las decenas es la segunda de la parte entera contando desde la derecha." },



// Puedes seguir añadiendo hasta 50 siguiendo exactamente este formato.
 // RECUERDA: La última pregunta NO debe llevar coma después de su llave de cierre }.
];