var DATOS_BATERIA = [


 { id: 1, enunciado: "Are you ................. the bus?", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Transporte público" },
 { id: 2, enunciado: "Be quiet ................. class.", opciones: ["on", "at", "in", "-"], correcta:  2, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 3, enunciado: "Dad is ................. home today.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Hogar, colegio o universidad" },
 { id: 4, enunciado: "Don't sleep ................. class.", opciones: ["on", "at", "in", "-"], correcta:  2, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 5, enunciado: "Don't talk ................. the bus.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Transporte público" },
 { id: 6, enunciado: "He is ................. a big warehouse.", opciones: ["on", "at", "in", "-"], correcta:  2, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 7, enunciado: "He is ................. the doctor's.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Actividades, empresas o negocios" },
 { id: 8, enunciado: "He is ................. the house.", opciones: ["on", "at", "in", "-"], correcta:  2, observaciones: "Espacios cerrados" },
 { id: 9, enunciado: "He is ................. the supermarket.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Actividades, empresas o negocios" },
 { id: 10, enunciado: "He is ................. the tram.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Transporte público" },
 { id: 11, enunciado: "He is a student ................. university.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Hogar, colegio o universidad" },
 { id: 12, enunciado: "He is sitting ................. class.", opciones: ["on", "at", "in", "-"], correcta:  2, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 13, enunciado: "He is sitting ................. his desk.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Un punto específico" },
 { id: 14, enunciado: "He is standing ................. the door.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Un punto específico" },
 { id: 15, enunciado: "He is waiting ................. 5 Station Road.", opciones: ["in", "at", "on", "-"], correcta:  1, observaciones: "Para direcciones (con número)" },
 { id: 16, enunciado: "He lives ................. 853 Sheffield Road.", opciones: ["in", "at", "on", "-"], correcta:  1, observaciones: "Para direcciones (con número)" },
 { id: 17, enunciado: "He sits ................. the edge of the lake.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Posición junto a río, costa o lago" },
 { id: 18, enunciado: "He works ................. a hospital.", opciones: ["on", "at", "in", "-"], correcta:  2, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 19, enunciado: "He works ................. Japan.", opciones: ["on", "at", "in", "-"], correcta:  2, observaciones: "Países y ciudades" },
 { id: 20, enunciado: "I am ................. class until four.", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 21, enunciado: "I am ................. Macy's buying a shirt.", opciones: ["in", "at", "on", "-"], correcta:  1, observaciones: "Actividades, empresas o negocios" },
 { id: 22, enunciado: "I am ................. Mary's party.", opciones: ["in", "at", "on", "-"], correcta:  1, observaciones: "Actividades, empresas o negocios" },
 { id: 23, enunciado: "I am ................. the bus right now.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Transporte público" },
 { id: 24, enunciado: "I am waiting ................. the bus stop.", opciones: ["in", "at", "on", "-"], correcta:  1, observaciones: "Un punto específico" },
 { id: 25, enunciado: "I forgot my bag ................. the train.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Transporte público" },
 { id: 26, enunciado: "I have money ................. my pocket.", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Espacios cerrados" },
 { id: 27, enunciado: "I live ................. Spain.", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Países y ciudades" },
 { id: 28, enunciado: "I see a spider ................. the wall.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Punto en una superficie" },
 { id: 29, enunciado: "I stay ................. 7 Sunset Blvd.", opciones: ["in", "at", "on", "-"], correcta:  1, observaciones: "Para direcciones (con número)" },
 { id: 30, enunciado: "I study ................. school.", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Hogar, colegio o universidad" },
 { id: 31, enunciado: "I was born ................. Mexico.", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Países y ciudades" },
 { id: 32, enunciado: "I'll be ................. the reception.", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Un punto específico" },
 { id: 33, enunciado: "Is he ................. the workshop?", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 34, enunciado: "Is she ................. home?", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Hogar, colegio o universidad" },
 { id: 35, enunciado: "Is your apartment ................. the fourth floor?", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Piso o planta de un edificio" },
 { id: 36, enunciado: "It is cold ................. Canada.", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Países y ciudades" },
 { id: 37, enunciado: "It is hot ................. the coach.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Transporte público" },
 { id: 38, enunciado: "It's raining ................. Berlin.", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Países y ciudades" },
 { id: 39, enunciado: "London is ................. the river Thames.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Posición junto a río, costa o lago" },
 { id: 40, enunciado: "Look ................. the top of the page.", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Un punto específico" },
 { id: 41, enunciado: "Look at the map ................. the board.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Punto en una superficie" },
 { id: 42, enunciado: "Many cities are ................. the Nile.", opciones: ["on", "in", "at", "-"], correcta:  0, observaciones: "Posición junto a río, costa o lago" },
 { id: 43, enunciado: "Meet me ................. 10 Park Street.", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Para direcciones (con número)" },
 { id: 44, enunciado: "Meet me ................. the cinema.", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Actividades, empresas o negocios" },
 { id: 45, enunciado: "Meet me ................. the entrance.", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Un punto específico" },
 { id: 46, enunciado: "My brother is ................. home.", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Hogar, colegio o universidad" },
 { id: 47, enunciado: "My friend lives ................. New York.", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Países y ciudades" },
 { id: 48, enunciado: "My keys are ................. my bag.", opciones: ["at", "on", "in", "-"], correcta:  2, observaciones: "Espacios cerrados" },
 { id: 49, enunciado: "My mom is ................. the office.", opciones: ["at", "in", "on", "-"], correcta:  1, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 50, enunciado: "My office is ................. the second floor.", opciones: ["in", "on", "at", "-"], correcta:  1, observaciones: "Piso o planta de un edificio" },
 { id: 51, enunciado: "My sister is ................. the laboratory.", opciones: ["at", "in", "on", "-"], correcta:  1, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 52, enunciado: "New York is ................. the East Coast.", opciones: ["in", "on", "at", "-"], correcta:  1, observaciones: "Posición junto a río, costa o lago" },
 { id: 53, enunciado: "No phones ................. class.", opciones: ["at", "in", "on", "-"], correcta:  1, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 54, enunciado: "Our house is ................. 15 River Way.", opciones: ["in", "on", "at", "-"], correcta:  2, observaciones: "Para direcciones (con número)" },
 { id: 55, enunciado: "Put the plate ................. the desk.", opciones: ["in", "on", "at", "-"], correcta:  1, observaciones: "Punto en una superficie" },
 { id: 56, enunciado: "See you ................. the corner.", opciones: ["on", "in", "at", "-"], correcta:  2, observaciones: "Un punto específico" },
 { id: 57, enunciado: "Send the letter ................. 24 Oak Street.", opciones: ["on", "in", "at", "-"], correcta:  2, observaciones: "Para direcciones (con número)" },
 { id: 58, enunciado: "She is ................. a factory.", opciones: ["at", "in", "on", "-"], correcta:  1, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 59, enunciado: "She is ................. her English class.", opciones: ["at", "in", "on", "-"], correcta:  1, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 60, enunciado: "She is ................. Paris.", opciones: ["on", "in", "at", "-"], correcta:  1, observaciones: "Países y ciudades" },
 { id: 61, enunciado: "She is ................. the end of the hall.", opciones: ["on", "in", "at", "-"], correcta:  2, observaciones: "Un punto específico" },
 { id: 62, enunciado: "She is ................. the hairdresser's.", opciones: ["on", "in", "at", "-"], correcta:  2, observaciones: "Actividades, empresas o negocios" },
 { id: 63, enunciado: "She is ................. the kitchen.", opciones: ["on", "in", "at", "-"], correcta:  1, observaciones: "Espacios cerrados" },
 { id: 64, enunciado: "She is ................. university.", opciones: ["on", "in", "at", "-"], correcta:  2, observaciones: "Hogar, colegio o universidad" },
 { id: 65, enunciado: "She is reading ................. the subway.", opciones: ["in", "on", "at", "-"], correcta:  1, observaciones: "Transporte público" },
 { id: 66, enunciado: "She lives ................. the top floor.", opciones: ["in", "on", "at", "-"], correcta:  1, observaciones: "Piso o planta de un edificio" },
 { id: 67, enunciado: "She spends all day ................. the office.", opciones: ["on", "in", "at", "-"], correcta:  1, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 68, enunciado: "She works ................. Google.", opciones: ["in", "at", "on", "-"], correcta:  1, observaciones: "Actividades, empresas o negocios" },
 { id: 69, enunciado: "Sit down ................. the chair.", opciones: ["at", "on", "in", "-"], correcta:  1, observaciones: "Punto en una superficie" },
 { id: 70, enunciado: "Stay ................. home if you are sick.", opciones: ["on", "at", "in", "-"], correcta:  1, observaciones: "Hogar, colegio o universidad" },
 { id: 71, enunciado: "The bird is ................. the cage.", opciones: ["on", "in", "at", "-"], correcta:  1, observaciones: "Espacios cerrados" },
 { id: 72, enunciado: "The book is ................. the table.", opciones: ["at", "on", "in", "-"], correcta:  1, observaciones: "Punto en una superficie" },
 { id: 73, enunciado: "The cafeteria is ................. the basement floor.", opciones: ["at", "on", "in", "-"], correcta:  1, observaciones: "Piso o planta de un edificio" },
 { id: 74, enunciado: "The cat is sleeping ................. the sofa.", opciones: ["at", "on", "in", "-"], correcta:  1, observaciones: "Punto en una superficie" },
 { id: 75, enunciado: "The dog is ................. the garden.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Espacios cerrados" },
 { id: 76, enunciado: "The gym is ................. the ground floor.", opciones: ["at", "on", "in", "-"], correcta:  1, observaciones: "Piso o planta de un edificio" },
 { id: 77, enunciado: "The hotel is ................. the beach.", opciones: ["at", "on", "in", "-"], correcta:  1, observaciones: "Posición junto a río, costa o lago" },
 { id: 78, enunciado: "The keys are ................. the counter.", opciones: ["at", "on", "in", "-"], correcta:  1, observaciones: "Punto en una superficie" },
 { id: 79, enunciado: "The meeting is ................. the tenth floor.", opciones: ["at", "on", "in", "-"], correcta:  1, observaciones: "Piso o planta de un edificio" },
 { id: 80, enunciado: "The office is ................. 55 Fifth Avenue.", opciones: ["on", "at", "in", "-"], correcta:  1, observaciones: "Para direcciones (con número)" },
 { id: 81, enunciado: "The park is ................. the riverside.", opciones: ["at", "in", "on", "-"], correcta:  2, observaciones: "Posición junto a río, costa o lago" },
 { id: 82, enunciado: "The party is ................. 100 West Road.", opciones: ["on", "at", "in", "-"], correcta:  1, observaciones: "Para direcciones (con número)" },
 { id: 83, enunciado: "The shop is ................. 12 Greenland Ave.", opciones: ["on", "at", "in", "-"], correcta:  1, observaciones: "Para direcciones (con número)" },
 { id: 84, enunciado: "The students are ................. class.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 85, enunciado: "The toys are ................. the box.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Espacios cerrados" },
 { id: 86, enunciado: "There are many people ................. the plane.", opciones: ["at", "in", "on", "-"], correcta:  2, observaciones: "Transporte público" },
 { id: 87, enunciado: "There is a balcony ................. every floor.", opciones: ["at", "in", "on", "-"], correcta:  2, observaciones: "Piso o planta de un edificio" },
 { id: 88, enunciado: "There is a cafe ................. the river bank.", opciones: ["at", "in", "on", "-"], correcta:  2, observaciones: "Posición junto a río, costa o lago" },
 { id: 89, enunciado: "There is a pen ................. the floor.", opciones: ["at", "in", "on", "-"], correcta:  2, observaciones: "Punto en una superficie" },
 { id: 90, enunciado: "There is a picture ................. the fridge.", opciones: ["at", "in", "on", "-"], correcta:  2, observaciones: "Punto en una superficie" },
 { id: 91, enunciado: "There is water ................. the glass.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Espacios cerrados" },
 { id: 92, enunciado: "They are ................. a concert.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Actividades, empresas o negocios" },
 { id: 93, enunciado: "They are ................. history class.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 94, enunciado: "They are ................. London.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Países y ciudades" },
 { id: 95, enunciado: "They are ................. school now.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Hogar, colegio o universidad" },
 { id: 96, enunciado: "They are ................. the clinic.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 97, enunciado: "They are ................. the fifth floor.", opciones: ["at", "in", "on", "-"], correcta:  2, observaciones: "Piso o planta de un edificio" },
 { id: 98, enunciado: "They are working ................. a bank.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 99, enunciado: "They have a house ................. the coast.", opciones: ["at", "in", "on", "-"], correcta:  2, observaciones: "Posición junto a río, costa o lago" },
 { id: 100, enunciado: "They live ................. 42 Blue Lane.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Para direcciones (con número)" },
 { id: 101, enunciado: "Turn left ................. the traffic lights.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Un punto específico" },
 { id: 102, enunciado: "Wait ................. the gate.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Un punto específico" },
 { id: 103, enunciado: "Wait ................. the room.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Espacios cerrados" },
 { id: 104, enunciado: "We are ................. a football match.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Actividades, empresas o negocios" },
 { id: 105, enunciado: "We are ................. college.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Hogar, colegio o universidad" },
 { id: 106, enunciado: "We are ................. the baker's.", opciones: ["at", "in", "on", "-"], correcta:  0, observaciones: "Actividades, empresas o negocios" },
 { id: 107, enunciado: "We are ................. the studio.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Lugares de trabajo (como ubicación)" },
 { id: 108, enunciado: "We are learning ................. class.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 109, enunciado: "We are sitting ................. the car.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Espacios cerrados" },
 { id: 110, enunciado: "We are traveling ................. a train.", opciones: ["in", "at", "on", "-"], correcta:  2, observaciones: "Transporte público" },
 { id: 111, enunciado: "We are traveling ................. Italy.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Países y ciudades" },
 { id: 112, enunciado: "We have a test ................. class today.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Para clase (dentro del aula/actividad)" },
 { id: 113, enunciado: "We learn English ................. school.", opciones: ["at", "on", "on", "-"], correcta:  0, observaciones: "Hogar, colegio o universidad" },
 { id: 114, enunciado: "We live ................. the lake.", opciones: ["in", "at", "on", "-"], correcta:  2, observaciones: "Posición junto a río, costa o lago" },
 { id: 115, enunciado: "We met ................. a ship.", opciones: ["in", "at", "on", "-"], correcta:  2, observaciones: "Transporte público" },
 { id: 116, enunciado: "We stay ................. Madrid.", opciones: ["in", "at", "on", "-"], correcta:  0, observaciones: "Países y ciudades" },
 { id: 117, enunciado: "We walked ................. the shore.", opciones: ["in", "at", "on", "-"], correcta:  2, observaciones: "Posición junto a río, costa o lago" },
 { id: 118, enunciado: "We work ................. the third floor.", opciones: ["in", "at", "on", "-"], correcta:  2, observaciones: "Piso o planta de un edificio" },
 { id: 119, enunciado: "Your phone is ................. the bed.", opciones: ["in", "at", "on", "-"], correcta:  2, observaciones: "Punto en una superficie" },
 { id: 120, enunciado: "Your room is ................. the first floor.", opciones: ["in", "at", "on", "-"], correcta:  2, observaciones: "Piso o planta de un edificio" }



];
