
// La hora en francés


var DATOS_BATERIA = [
 { id: 1, enunciado: "03-10.png", opciones: ["Il est une heure", "Il est cinq heures vingt", "Il est trois heures dix", "Il est quatre heures et quart"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 2, enunciado: "09-30.png", opciones: ["Il est douze heures moins vingt", "Il est six heures vingt-cinq", "Il est neuf heures et demie", "Il est douze heures moins dix"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 3, enunciado: "09-40.png", opciones: ["Il est quatre heures vingt-cinq", "Il est dix heures vingt", "Il est dix heures moins vingt", "Il est dix heures"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 4, enunciado: "01-20.png", opciones: ["Il est neuf heures cinq", "Il est sept heures moins le quart", "Il est une heure vingt", "Il est onze heures moins le quart"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 5, enunciado: "03-30.png", opciones: ["Il est six heures et quart", "Il est sept heures et demie", "Il est trois heures et demie", "Il est douze heures dix"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 6, enunciado: "05-35.png", opciones: ["Il est sept heures moins dix", "Il est cinq heures dix", "Il est six heures moins vingt-cinq", "Il est huit heures vingt-cinq"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 7, enunciado: "02-10.png", opciones: ["Il est trois heures moins vingt", "Il est deux heures cinq", "Il est deux heures dix", "Il est trois heures vingt-cinq"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 8, enunciado: "02-50.png", opciones: ["Il est trois heures", "Il est cinq heures moins cinq", "Il est trois heures moins dix", "Il est deures moins vent-cinq"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 9, enunciado: "04-05.png", opciones: ["Il est deux heures et quart", "Il est une heure et quart", "Il est quatre heures cinq", "Il est onze heures moins vingt-cinq"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 10, enunciado: "12-55.png", opciones: ["Il est six heures moins le quart", "Il est neuf heures et quart", "Il est une heure moins cinq", "Il est onze heures et quart"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 11, enunciado: "08-35.png", opciones: ["Il est une heure", "Il est onze heures vingt-cinq", "Il est neuf heures moins vingt-cinq", "Il est neuf heures moins dix"], correcta:  2, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 12, enunciado: "01-05.png", opciones: ["Il est douze heures moins vingt", "Il est six heures", "Il est trois heures dix", "Il est une heure cinq"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 13, enunciado: "07-20.png", opciones: ["Il est quatre heures vingt-cinq", "Il est huit heures dix", "Il est neuf heures et demie", "Il est sept heures vingt"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 14, enunciado: "04-15.png", opciones: ["Il est neuf heures cinq", "Il est huit heures moins vingt", "Il est dix heures moins vingt", "Il est quatre heures et quart"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 15, enunciado: "11-50.png", opciones: ["Il est six heures et quart", "Il est une heure moins vingt", "Il est une heure vingt", "Il est douze heures moins dix"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 16, enunciado: "10-00.png", opciones: ["Il est sept heures moins dix", "Il est sept heures cinq", "Il est trois heures et demie", "Il est dix heures"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 17, enunciado: "10-45.png", opciones: ["Il est trois heures moins vingt", "Il est cinq heures vingt", "Il est six heures moins vingt-cinq", "Il est onze heures moins le quart"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 18, enunciado: "12-10.png", opciones: ["Il est trois heures", "Il est six heures vingt-cinq", "Il est deux heures dix", "Il est douze heures dix"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 19, enunciado: "08-25.png", opciones: ["Il est deux heures et quart", "Il est dix heures vingt", "Il est trois heures moins dix", "Il est huit heures vingt-cinq"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 20, enunciado: "03-25.png", opciones: ["Il est six heures moins le quart", "Il est sept heures moins le quart", "Il est quatre heures cinq", "Il est trois heures vingt-cinq"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 21, enunciado: "01-35.png", opciones: ["Il est une heure", "Il est sept heures et demie", "Il est une heure moins cinq", "Il est deures moins vent-cinq"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 22, enunciado: "10-35.png", opciones: ["Il est douze heures moins vingt", "Il est cinq heures dix", "Il est neuf heures moins vingt-cinq", "Il est onze heures moins vingt-cinq"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 23, enunciado: "11-15.png", opciones: ["Il est quatre heures vingt-cinq", "Il est deux heures cinq", "Il est trois heures dix", "Il est onze heures et quart"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 24, enunciado: "08-50.png", opciones: ["Il est neuf heures cinq", "Il est cinq heures moins cinq", "Il est neuf heures et demie", "Il est neuf heures moins dix"], correcta:  3, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 25, enunciado: "12-40.png", opciones: ["Il est six heures et quart", "Il est une heure moins vingt", "Il est dix heures moins vingt", "Il est une heure cinq"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 26, enunciado: "07-05.png", opciones: ["Il est sept heures moins dix", "Il est sept heures cinq", "Il est une heure vingt", "Il est sept heures vingt"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 27, enunciado: "05-20.png", opciones: ["Il est trois heures moins vingt", "Il est cinq heures vingt", "Il est trois heures et demie", "Il est quatre heures et quart"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 28, enunciado: "06-25.png", opciones: ["Il est trois heures", "Il est six heures vingt-cinq", "Il est six heures moins vingt-cinq", "Il est douze heures moins dix"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 29, enunciado: "10-20.png", opciones: ["Il est deux heures et quart", "Il est dix heures vingt", "Il est deux heures dix", "Il est dix heures"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 30, enunciado: "06-45.png", opciones: ["Il est six heures moins le quart", "Il est sept heures moins le quart", "Il est trois heures moins dix", "Il est onze heures moins le quart"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 31, enunciado: "07-30.png", opciones: ["Il est une heure", "Il est sept heures et demie", "Il est quatre heures cinq", "Il est douze heures dix"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 32, enunciado: "05-10.png", opciones: ["Il est douze heures moins vingt", "Il est cinq heures dix", "Il est une heure moins cinq", "Il est huit heures vingt-cinq"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 33, enunciado: "02-05.png", opciones: ["Il est quatre heures vingt-cinq", "Il est deux heures cinq", "Il est neuf heures moins vingt-cinq", "Il est trois heures vingt-cinq"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 34, enunciado: "04-55.png", opciones: ["Il est neuf heures cinq", "Il est cinq heures moins cinq", "Il est trois heures dix", "Il est deures moins vent-cinq"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 35, enunciado: "01-15.png", opciones: ["Il est six heures et quart", "Il est une heure et quart", "Il est neuf heures et demie", "Il est onze heures moins vingt-cinq"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 36, enunciado: "09-15.png", opciones: ["Il est sept heures moins dix", "Il est neuf heures et quart", "Il est dix heures moins vingt", "Il est onze heures et quart"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 37, enunciado: "11-25.png", opciones: ["Il est trois heures moins vingt", "Il est onze heures vingt-cinq", "Il est une heure vingt", "Il est neuf heures moins dix"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 38, enunciado: "06-00.png", opciones: ["Il est trois heures", "Il est six heures", "Il est trois heures et demie", "Il est une heure cinq"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 39, enunciado: "08-10.png", opciones: ["Il est deux heures et quart", "Il est huit heures dix", "Il est six heures moins vingt-cinq", "Il est sept heures vingt"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 40, enunciado: "07-40.png", opciones: ["Il est six heures moins le quart", "Il est huit heures moins vingt", "Il est deux heures dix", "Il est quatre heures et quart"], correcta:  1, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 41, enunciado: "01-00.png", opciones: ["Il est une heure", "Il est une heure moins vingt", "Il est trois heures moins dix", "Il est douze heures moins dix"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 42, enunciado: "11-40.png", opciones: ["Il est douze heures moins vingt", "Il est sept heures cinq", "Il est quatre heures cinq", "Il est dix heures"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 43, enunciado: "04-25.png", opciones: ["Il est quatre heures vingt-cinq", "Il est cinq heures vingt", "Il est une heure moins cinq", "Il est onze heures moins le quart"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 44, enunciado: "09-05.png", opciones: ["Il est neuf heures cinq", "Il est six heures vingt-cinq", "Il est neuf heures moins vingt-cinq", "Il est douze heures dix"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 45, enunciado: "06-15.png", opciones: ["Il est six heures et quart", "Il est dix heures vingt", "Il est trois heures dix", "Il est huit heures vingt-cinq"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 46, enunciado: "06-50.png", opciones: ["Il est sept heures moins dix", "Il est sept heures moins le quart", "Il est neuf heures et demie", "Il est trois heures vingt-cinq"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 47, enunciado: "02-40.png", opciones: ["Il est trois heures moins vingt", "Il est sept heures et demie", "Il est dix heures moins vingt", "Il est deures moins vent-cinq"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 48, enunciado: "03-00.png", opciones: ["Il est trois heures", "Il est cinq heures dix", "Il est une heure vingt", "Il est onze heures moins vingt-cinq"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 49, enunciado: "02-15.png", opciones: ["Il est deux heures et quart", "Il est deux heures cinq", "Il est trois heures et demie", "Il est onze heures et quart"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },
 { id: 50, enunciado: "05-45.png", opciones: ["Il est six heures moins le quart", "Il est cinq heures moins cinq", "Il est six heures moins vingt-cinq", "Il est neuf heures moins dix"], correcta:  0, observaciones: "La aguja larga marca los minutos y la corta las horas" },






// Puedes seguir añadiendo hasta 50 siguiendo exactamente este formato.
 // RECUERDA: La última pregunta NO debe llevar coma después de su llave de cierre }.
]