var DATOS_BATERIA = [
 { id: 1, enunciado: "La palabra ABAJO es un adverbio de: ", opciones: ["Lugar", "Tiempo", "Modo", "Duda"], correcta:  0, observaciones: "Indica una posición inferior." },
 { id: 2, enunciado: "La palabra ACASO es un adverbio de: ", opciones: ["Duda", "Cantidad", "Lugar", "Negación"], correcta:  0, observaciones: "Expresa incertidumbre." },
 { id: 3, enunciado: "La palabra AHORA es un adverbio de: ", opciones: ["Tiempo", "Modo", "Afirmación", "Cantidad"], correcta:  0, observaciones: "Se refiere al momento actual." },
 { id: 4, enunciado: "La palabra ALLÍ es un adverbio de: ", opciones: ["Lugar", "Negación", "Tiempo", "Modo"], correcta:  0, observaciones: "Señala un lugar lejano." },
 { id: 5, enunciado: "La palabra AQUÍ es un adverbio de: ", opciones: ["Lugar", "Duda", "Cantidad", "Afirmación"], correcta:  0, observaciones: "Señala el lugar del hablante." },
 { id: 6, enunciado: "La palabra ARRIBA es un adverbio de: ", opciones: ["Tiempo", "Lugar", "Modo", "Negación"], correcta:  1, observaciones: "Indica una posición elevada." },
 { id: 7, enunciado: "La palabra ASÍ es un adverbio de: ", opciones: ["Cantidad", "Modo", "Tiempo", "Duda"], correcta:  1, observaciones: "Indica la manera de algo." },
 { id: 8, enunciado: "La palabra AYER es un adverbio de: ", opciones: ["Modo", "Tiempo", "Afirmación", "Lugar"], correcta:  1, observaciones: "Indica el día anterior al hoy." },
 { id: 9, enunciado: "La palabra BASTANTE es un adverbio de: ", opciones: ["Duda", "Cantidad", "Modo", "Tiempo"], correcta:  1, observaciones: "Indica una cuantía suficiente." },
 { id: 10, enunciado: "La palabra BIEN es un adverbio de: ", opciones: ["Negación", "Modo", "Cantidad", "Lugar"], correcta:  1, observaciones: "Indica una manera positiva." },
 { id: 11, enunciado: "La palabra CERCA es un adverbio de: ", opciones: ["Tiempo", "Lugar", "Duda", "Afirmación"], correcta:  1, observaciones: "Indica proximidad espacial." },
 { id: 12, enunciado: "La palabra CIERTAMENTE es un adverbio de: ", opciones: ["Modo", "Afirmación", "Tiempo", "Negación"], correcta:  1, observaciones: "Asegura la verdad de algo." },
 { id: 13, enunciado: "La palabra DELANTE es un adverbio de: ", opciones: ["Cantidad", "Lugar", "Modo", "Tiempo"], correcta:  1, observaciones: "Indica posición anterior." },
 { id: 14, enunciado: "La palabra DEMASIADO es un adverbio de: ", opciones: ["Duda", "Cantidad", "Afirmación", "Lugar"], correcta:  1, observaciones: "Indica un exceso." },
 { id: 15, enunciado: "La palabra DETRÁS es un adverbio de: ", opciones: ["Tiempo", "Modo", "Lugar", "Cantidad"], correcta:  2, observaciones: "Indica posición posterior." },
 { id: 16, enunciado: "La palabra EFECTIVAMENTE es un adverbio de: ", opciones: ["Lugar", "Duda", "Afirmación", "Tiempo"], correcta:  2, observaciones: "Valida o confirma un hecho." },
 { id: 17, enunciado: "La palabra ENTONCES es un adverbio de: ", opciones: ["Modo", "Cantidad", "Tiempo", "Negación"], correcta:  2, observaciones: "Indica un tiempo específico." },
 { id: 18, enunciado: "La palabra HOY es un adverbio de: ", opciones: ["Lugar", "Afirmación", "Tiempo", "Duda"], correcta:  2, observaciones: "Indica el día presente." },
 { id: 19, enunciado: "La palabra JAMÁS es un adverbio de: ", opciones: ["Tiempo", "Modo", "Negación", "Cantidad"], correcta:  2, observaciones: "Niega de forma rotunda." },
 { id: 20, enunciado: "La palabra LEJOS es un adverbio de: ", opciones: ["Cantidad", "Tiempo", "Lugar", "Modo"], correcta:  2, observaciones: "Indica distancia grande." },
 { id: 21, enunciado: "La palabra MAL es un adverbio de: ", opciones: ["Afirmación", "Duda", "Modo", "Tiempo"], correcta:  2, observaciones: "Indica una manera negativa." },
 { id: 22, enunciado: "La palabra MÁS es un adverbio de: ", opciones: ["Negación", "Lugar", "Cantidad", "Tiempo"], correcta:  2, observaciones: "Indica superioridad numérica." },
 { id: 23, enunciado: "La palabra MEJOR es un adverbio de: ", opciones: ["Tiempo", "Cantidad", "Modo", "Duda"], correcta:  2, observaciones: "Grado comparativo de bien." },
 { id: 24, enunciado: "La palabra MENOS es un adverbio de: ", opciones: ["Lugar", "Afirmación", "Cantidad", "Modo"], correcta:  2, observaciones: "Indica inferioridad numérica." },
 { id: 25, enunciado: "La palabra MUCHO es un adverbio de: ", opciones: ["Modo", "Tiempo", "Cantidad", "Negación"], correcta:  2, observaciones: "Indica abundancia." },
 { id: 26, enunciado: "La palabra MUY es un adverbio de: ", opciones: ["Duda", "Lugar", "Cantidad", "Afirmación"], correcta:  2, observaciones: "Aumenta el grado de un adjetivo/adverbio." },
 { id: 27, enunciado: "La palabra NADA es un adverbio de: ", opciones: ["Modo", "Tiempo", "Lugar", "Cantidad"], correcta:  3, observaciones: "Indica cantidad inexistente." },
 { id: 28, enunciado: "La palabra NO es un adverbio de: ", opciones: ["Duda", "Cantidad", "Afirmación", "Negación"], correcta:  3, observaciones: "Es la negación básica." },
 { id: 29, enunciado: "La palabra NUNCA es un adverbio de: ", opciones: ["Modo", "Lugar", "Afirmación", "Tiempo"], correcta:  3, observaciones: "Indica en ningún momento." },
 { id: 30, enunciado: "La palabra PEOR es un adverbio de: ", opciones: ["Cantidad", "Tiempo", "Lugar", "Modo"], correcta:  3, observaciones: "Grado comparativo de mal." },
 { id: 31, enunciado: "La palabra POCO es un adverbio de: ", opciones: ["Duda", "Modo", "Tiempo", "Cantidad"], correcta:  3, observaciones: "Indica escasez." },
 { id: 32, enunciado: "La palabra POSIBLEMENTE es un adverbio de: ", opciones: ["Afirmación", "Tiempo", "Lugar", "Duda"], correcta:  3, observaciones: "Indica probabilidad." },
 { id: 33, enunciado: "La palabra PROBABLEMENTE es un adverbio de: ", opciones: ["Negación", "Cantidad", "Modo", "Duda"], correcta:  3, observaciones: "Expresa una suposición." },
 { id: 34, enunciado: "La palabra QUIZÁ es un adverbio de: ", opciones: ["Tiempo", "Lugar", "Afirmación", "Duda"], correcta:  3, observaciones: "Indica duda o posibilidad." },
 { id: 35, enunciado: "La palabra RÁPIDAMENTE es un adverbio de: ", opciones: ["Cantidad", "Negación", "Tiempo", "Modo"], correcta:  3, observaciones: "Indica velocidad en la acción." },
 { id: 36, enunciado: "La palabra SÍ es un adverbio de: ", opciones: ["Duda", "Cantidad", "Tiempo", "Afirmación"], correcta:  3, observaciones: "Se usa para asentir." },
 { id: 37, enunciado: "La palabra SIEMPRE es un adverbio de: ", opciones: ["Modo", "Lugar", "Negación", "Tiempo"], correcta:  3, observaciones: "Indica constancia temporal." },
 { id: 38, enunciado: "La palabra TAMPOCO es un adverbio de: ", opciones: ["Tiempo", "Modo", "Cantidad", "Negación"], correcta:  3, observaciones: "Niega sumándose a otra negación." },
 { id: 39, enunciado: "La palabra YA es un adverbio de: ", opciones: ["Lugar", "Duda", "Modo", "Tiempo"], correcta:  3, observaciones: "Indica inmediatez o pasado." },
 { id: 40, enunciado: "Señala el adverbio de MODO.", opciones: ["Quizá", "Cerca", "Ayer", "Despacio"], correcta:  3, observaciones: "Despacio explica la manera o cómo se hace una acción." },
 { id: 41, enunciado: "Señala el adverbio de LUGAR.", opciones: ["Después", "Muy", "Efectivamente", "Allí"], correcta:  3, observaciones: "Allí señala un lugar que está lejos de nosotros." },
 { id: 42, enunciado: "Señala el adverbio de MODO.", opciones: ["Jamás", "Cerca", "Temprano", "Rápido"], correcta:  3, observaciones: "Rápido nos cuenta la velocidad o manera en que alguien se mueve." },
 { id: 43, enunciado: "Señala el adverbio de CANTIDAD.", opciones: ["Sí", "Mañana", "Abajo", "Mucho"], correcta:  3, observaciones: "Mucho lo usamos cuando hay una cantidad grande de algo." },
 { id: 44, enunciado: "Señala el adverbio de NEGACIÓN.", opciones: ["Bien", "Pronto", "Más", "No"], correcta:  3, observaciones: "No es la palabra que usamos para decir que algo no es así." },
 { id: 45, enunciado: "Señala el adverbio de DUDA.", opciones: ["Nunca", "Allí", "Rápidamente", "Quizá"], correcta:  3, observaciones: "Quizá expresa que algo es posible pero no estamos seguros." },
 { id: 46, enunciado: "Señala el adverbio de TIEMPO.", opciones: ["Poco", "Claramente", "Seguramente", "Ayer"], correcta:  3, observaciones: "Ayer nos indica que algo ocurrió el día anterior." },
 { id: 47, enunciado: "Señala el adverbio de CANTIDAD.", opciones: ["Nunca", "Fuera", "Mañana", "Bastante"], correcta:  3, observaciones: "Bastante significa que hay una cantidad suficiente de algo." },
 { id: 48, enunciado: "Señala el adverbio de AFIRMACIÓN.", opciones: ["Tampoco", "Casi", "Debajo", "Cierto"], correcta:  3, observaciones: "Cierto confirma que lo que decimos es verdad." },
 { id: 49, enunciado: "Señala el adverbio de NEGACIÓN.", opciones: ["Muy", "Detrás", "Luego", "Nunca"], correcta:  3, observaciones: "Nunca significa que algo no pasa en ningún momento." },
 { id: 50, enunciado: "Señala el adverbio de DUDA.", opciones: ["Sí", "Mal", "Lejos", "Tal vez"], correcta:  3, observaciones: "Tal vez se usa cuando tenemos una duda sobre algo." },
 { id: 51, enunciado: "Señala el adverbio de LUGAR.", opciones: ["Mucho", "Hoy", "No", "Lejos"], correcta:  3, observaciones: "Lejos significa que algo está a mucha distancia." },
 { id: 52, enunciado: "Señala el adverbio de TIEMPO.", opciones: ["Bien", "Aquí", "Quizá", "Mañana"], correcta:  3, observaciones: "Mañana indica que algo pasará el día siguiente a hoy." },
 { id: 53, enunciado: "Señala el adverbio de MODO.", opciones: ["Siempre", "Cerca", "Bastante", "Mal"], correcta:  3, observaciones: "Mal indica que algo no se hizo de la forma adecuada." },
 { id: 54, enunciado: "Señala el adverbio de CANTIDAD.", opciones: ["Jamás", "Arriba", "Temprano", "Más"], correcta:  3, observaciones: "Más se usa para añadir cantidad a algo." },
 { id: 55, enunciado: "Señala el adverbio de AFIRMACIÓN.", opciones: ["No", "Pronto", "Menos", "Exacto"], correcta:  3, observaciones: "Exacto se dice cuando algo es totalmente verdad o correcto." },
 { id: 56, enunciado: "Señala el adverbio de NEGACIÓN.", opciones: ["Muy", "Fuera", "Jamás", "Luego"], correcta:  2, observaciones: "Jamás es otra forma de decir que algo no pasará nunca." },
 { id: 57, enunciado: "Señala el adverbio de DUDA.", opciones: ["Sí", "Deprisa", "Posiblemente", "Abajo"], correcta:  2, observaciones: "Posiblemente indica que algo puede que ocurra." },
 { id: 58, enunciado: "Señala el adverbio de LUGAR.", opciones: ["Tarde", "Muy", "Arriba", "También"], correcta:  2, observaciones: "Arriba nos indica que algo está en un lugar más alto." },
 { id: 59, enunciado: "Señala el adverbio de TIEMPO.", opciones: ["Poco", "Claramente", "Luego", "Cierto"], correcta:  2, observaciones: "Luego indica que algo pasará después." },
 { id: 60, enunciado: "Señala el adverbio de MODO.", opciones: ["Nunca", "Allí", "Mejor", "Mañana"], correcta:  2, observaciones: "Mejor compara la forma de hacer algo de manera superior." },
 { id: 61, enunciado: "Señala el adverbio de CANTIDAD.", opciones: ["Sí", "Mañana", "Menos", "Fuera"], correcta:  2, observaciones: "Menos se usa para quitar o reducir cantidad." },
 { id: 62, enunciado: "Señala el adverbio de AFIRMACIÓN.", opciones: ["Tampoco", "Casi", "Seguramente", "Debajo"], correcta:  2, observaciones: "Seguramente afirma algo con mucha confianza." },
 { id: 63, enunciado: "Señala el adverbio de NEGACIÓN.", opciones: ["Muy", "Detrás", "Nada", "Luego"], correcta:  2, observaciones: "Nada indica que no hay ninguna cantidad o cosa." },
 { id: 64, enunciado: "Señala el adverbio de DUDA.", opciones: ["Sí", "Mal", "Acaso", "Lejos"], correcta:  2, observaciones: "Acaso es una palabra que usamos para preguntar con duda." },
 { id: 65, enunciado: "Señala el adverbio de LUGAR.", opciones: ["Pronto", "Bastante", "Abajo", "Seguramente"], correcta:  2, observaciones: "Abajo nos indica que algo está en un lugar inferior." },
 { id: 66, enunciado: "Señala el adverbio de TIEMPO.", opciones: ["Poco", "Rápido", "Antes", "Sí"], correcta:  2, observaciones: "Antes nos dice que algo pasó en un tiempo anterior." },
 { id: 67, enunciado: "Señala el adverbio de MODO.", opciones: ["Peor", "Siempre", "Cerca", "Bastante"], correcta:  0, observaciones: "Peor indica que algo es de calidad inferior o se hizo mal." },
 { id: 68, enunciado: "Señala el adverbio de CANTIDAD.", opciones: ["Casi", "Jamás", "Arriba", "Temprano"], correcta:  0, observaciones: "Casi indica que falta muy poco para llegar a una cantidad." },
 { id: 69, enunciado: "Señala el adverbio de AFIRMACIÓN.", opciones: ["Efectivamente", "No", "Pronto", "Menos"], correcta:  0, observaciones: "Efectivamente confirma que algo es tal como se ha dicho." },
 { id: 70, enunciado: "Señala el adverbio de NEGACIÓN.", opciones: ["Ni", "Muy", "Fuera", "Luego"], correcta:  0, observaciones: "Ni se usa para negar dos cosas seguidas." },
 { id: 71, enunciado: "Señala el adverbio de DUDA.", opciones: ["Probablemente", "Sí", "Deprisa", "Abajo"], correcta:  0, observaciones: "Probablemente indica que hay muchas opciones de que algo sea así." },
 { id: 72, enunciado: "Señala el adverbio de LUGAR.", opciones: ["Fuera", "Tarde", "Muy", "También"], correcta:  0, observaciones: "Fuera nos indica que algo no está dentro de un lugar." },
 { id: 73, enunciado: "Señala el adverbio de TIEMPO.", opciones: ["Después", "Poco", "Claramente", "Cierto"], correcta:  0, observaciones: "Después señala un momento posterior en el tiempo." },
 { id: 74, enunciado: "Señala el adverbio de MODO.", opciones: ["Así", "Nunca", "Allí", "Mañana"], correcta:  0, observaciones: "Así explica la manera concreta en que se hace algo." },
 { id: 75, enunciado: "Señala el adverbio de CANTIDAD.", opciones: ["Tan", "Sí", "Mañana", "Fuera"], correcta:  0, observaciones: "Tan se usa para aumentar la importancia de una cantidad." },
 { id: 76, enunciado: "Señala el adverbio de AFIRMACIÓN.", opciones: ["Verdaderamente", "Tampoco", "Casi", "Debajo"], correcta:  0, observaciones: "Verdaderamente asegura que algo es real y de verdad." },
 { id: 77, enunciado: "Señala el adverbio de NEGACIÓN.", opciones: ["Para nada", "Muy", "Detrás", "Luego"], correcta:  0, observaciones: "Para nada es una forma fuerte de decir que no." },
 { id: 78, enunciado: "Señala el adverbio de DUDA.", opciones: ["Seguro", "Quizá", "Mal", "Lejos"], correcta:  0, observaciones: "Seguro (usado como duda o pregunta) busca confirmar algo." },
 { id: 79, enunciado: "Señala el adverbio de LUGAR.", opciones: ["Detrás", "Pronto", "Bastante", "Sí"], correcta:  0, observaciones: "Detrás nos indica que algo está en la parte de atrás." },
 { id: 80, enunciado: "Señala el adverbio de LUGAR.", opciones: ["Mañana", "Aquí", "Mucho", "Sí"], correcta:  1, observaciones: "Aquí nos indica en qué parte o lugar ocurre algo." },
 { id: 81, enunciado: "Señala el adverbio de AFIRMACIÓN.", opciones: ["Jamás", "También", "Arriba", "Rápido"], correcta:  1, observaciones: "También se usa para decir que algo es verdad o que se suma." },
 { id: 82, enunciado: "Señala el adverbio de DUDA.", opciones: ["Siempre", "A lo mejor", "Menos", "Debajo"], correcta:  1, observaciones: "A lo mejor se usa cuando no estamos seguros de algo." },
 { id: 83, enunciado: "Señala el adverbio de TIEMPO.", opciones: ["Mal", "Ahora", "Bastante", "Cierto"], correcta:  1, observaciones: "Ahora indica que la acción está pasando en este preciso momento." },
 { id: 84, enunciado: "Señala el adverbio de LUGAR.", opciones: ["Antes", "Cerca", "Casi", "También"], correcta:  1, observaciones: "Cerca indica que algo está a poca distancia de nosotros." },
 { id: 85, enunciado: "Señala el adverbio de TIEMPO.", opciones: ["Lejos", "Bien", "Hoy", "No"], correcta:  2, observaciones: "Hoy nos dice el momento o cuándo pasa algo." },
 { id: 86, enunciado: "Señala el adverbio de NEGACIÓN.", opciones: ["Pronto", "Bastante", "Tampoco", "Fuera"], correcta:  2, observaciones: "Tampoco sirve para negar algo o decir que no." },
 { id: 87, enunciado: "Señala el adverbio de AFIRMACIÓN.", opciones: ["No", "Quizá", "Sí", "Tarde"], correcta:  2, observaciones: "Sí es la palabra principal para asegurar que algo es verdad." },
 { id: 88, enunciado: "Señala el adverbio de MODO.", opciones: ["Nada", "Lejos", "Bien", "Todavía"], correcta:  2, observaciones: "Bien nos dice que una acción se hizo de forma correcta." },
 { id: 89, enunciado: "Señala el adverbio de CANTIDAD.", opciones: ["Nunca", "Allí", "Mal", "Poco"], correcta:  3, observaciones: "Poco sirve para decir cuánto hay de algo." },
 { id: 90, enunciado: "Señala la oración que contiene un adverbio de LUGAR.", opciones: ["Luis come pan", "Luis vive lejos", "Luis es alto", "Luis tiene sed"], correcta:  1, observaciones: "Lejos nos indica el lugar donde vive Luis." },
 { id: 91, enunciado: "Señala la oración que contiene un adverbio de LUGAR.", opciones: ["Ella salta", "El sol brilla", "Ponlo ahí", "Es de noche"], correcta:  2, observaciones: "Ahí señala un sitio específico para poner algo." },
 { id: 92, enunciado: "Señala la oración que contiene un adverbio de LUGAR.", opciones: ["Dame eso", "Mira arriba", "Juan corre", "Tengo sueño"], correcta:  1, observaciones: "Arriba nos dice hacia qué dirección o lugar mirar." },
 { id: 93, enunciado: "Señala la oración que contiene un adverbio de LUGAR.", opciones: ["Ven aquí", "El gato duerme", "Es azul", "Yo juego"], correcta:  0, observaciones: "Aquí indica el lugar exacto donde debe venir." },
 { id: 94, enunciado: "Señala la oración que contiene un adverbio de LUGAR.", opciones: ["Hace frío", "Está fuera", "Cierra esto", "Luis lee"], correcta:  1, observaciones: "Fuera nos dice que no está dentro del sitio." },
 { id: 95, enunciado: "Señala la oración que contiene un adverbio de TIEMPO.", opciones: ["Es grande", "Me gusta", "Llegó tarde", "Soy Luis"], correcta:  2, observaciones: "Tarde indica el momento en el que llegó." },
 { id: 96, enunciado: "Señala la oración que contiene un adverbio de TIEMPO.", opciones: ["Iré pronto", "Es bonito", "Dame agua", "Salta mucho"], correcta:  0, observaciones: "Pronto nos dice que pasará en poco tiempo." },
 { id: 97, enunciado: "Señala la oración que contiene un adverbio de TIEMPO.", opciones: ["Eres tú", "Hazlo ahora", "El perro ladra", "Es fácil"], correcta:  1, observaciones: "Ahora indica que hay que hacerlo en este momento." },
 { id: 98, enunciado: "Señala la oración que contiene un adverbio de TIEMPO.", opciones: ["Viene luego", "Está bien", "Es rojo", "Mira eso"], correcta:  0, observaciones: "Luego nos dice que pasará en un momento después." },
 { id: 99, enunciado: "Señala la oración que contiene un adverbio de TIEMPO.", opciones: ["Cenamos ya", "Es liso", "Pon la mesa", "Luis salta"], correcta:  0, observaciones: "Ya indica que la acción ocurre en este mismo instante." },
 { id: 100, enunciado: "Señala la oración que contiene un adverbio de MODO.", opciones: ["Habla bajito", "Tiene ocho", "Es mío", "Ve allí"], correcta:  0, observaciones: "Bajito nos dice la manera o el modo de hablar." },
 { id: 101, enunciado: "Señala la oración que contiene un adverbio de MODO.", opciones: ["Luis corre", "Escribe mal", "Dame el polo", "Hay luz"], correcta:  1, observaciones: "Mal nos cuenta cómo está escribiendo Luis." },
 { id: 102, enunciado: "Señala la oración que contiene un adverbio de MODO.", opciones: ["Es suyo", "Sube ya", "Pasea así", "Tiene calor"], correcta:  2, observaciones: "Así nos enseña la forma concreta de pasear." },
 { id: 103, enunciado: "Señala la oración que contiene un adverbio de MODO.", opciones: ["Grita fuerte", "Son cinco", "Mira esto", "Es verdad"], correcta:  0, observaciones: "Fuerte nos explica el modo en que está gritando." },
 { id: 104, enunciado: "Señala la oración que contiene un adverbio de MODO.", opciones: ["Lee deprisa", "Hay pan", "Ponlo ahí", "Es de Luis"], correcta:  0, observaciones: "Deprisa nos dice la velocidad o modo de leer." },
 { id: 105, enunciado: "Señala la oración que contiene un adverbio de CANTIDAD.", opciones: ["Come poco", "Es verde", "Sal de casa", "Mira allí"], correcta:  0, observaciones: "Poco nos indica la cantidad que está comiendo." },
 { id: 106, enunciado: "Señala la oración que contiene un adverbio de CANTIDAD.", opciones: ["Luis juega", "Sabe bastante", "Es el fin", "Ven pronto"], correcta:  1, observaciones: "Bastante nos dice que tiene mucha cantidad de saber." },
 { id: 107, enunciado: "Señala la oración que contiene un adverbio de CANTIDAD.", opciones: ["Duerme más", "Es de día", "Pelo corto", "No hables"], correcta:  0, observaciones: "Más pide aumentar la cantidad de sueño." },
 { id: 108, enunciado: "Señala la oración que contiene un adverbio de CANTIDAD.", opciones: ["Es caro", "Pesa menos", "Mira eso", "Ven aquí"], correcta:  1, observaciones: "Menos indica una cantidad pequeña de peso." },
 { id: 109, enunciado: "Señala la oración que contiene un adverbio de CANTIDAD.", opciones: ["Ríe mucho", "Es tarde", "Raya al lado", "Dame eso"], correcta:  0, observaciones: "Mucho nos dice que realiza la acción en gran cantidad." },
 { id: 110, enunciado: "Señala la oración que contiene un adverbio de AFIRMACIÓN.", opciones: ["Sí, quiero", "No voy", "Quizá llueva", "Está lejos"], correcta:  0, observaciones: "Sí sirve para afirmar lo que queremos." },
 { id: 111, enunciado: "Señala la oración que contiene un adverbio de AFIRMACIÓN.", opciones: ["Es feo", "Cierto, vino", "Dame luz", "Ve fuera"], correcta:  1, observaciones: "Cierto confirma que es verdad que esa persona vino." },
 { id: 112, enunciado: "Señala la oración que contiene un adverbio de AFIRMACIÓN.", opciones: ["Claro, iré", "No entres", "Es frío", "Mira bien"], correcta:  0, observaciones: "Claro se usa para afirmar con seguridad." },
 { id: 113, enunciado: "Señala la oración que contiene un adverbio de AFIRMACIÓN.", opciones: ["Es dulce", "También juego", "Vete ya", "Ponlo aquí"], correcta:  1, observaciones: "También afirma que se suma a la acción de jugar." },
 { id: 114, enunciado: "Señala la oración que contiene un adverbio de AFIRMACIÓN.", opciones: ["Seguro llega", "No mira", "Es rojo", "Ven tarde"], correcta:  0, observaciones: "Seguro afirma con mucha confianza que llegará." },
 { id: 115, enunciado: "Señala la oración que contiene un adverbio de NEGACIÓN.", opciones: ["No cantes", "Es bueno", "Mira arriba", "Come pan"], correcta:  0, observaciones: "No sirve para negar la acción de cantar." },
 { id: 116, enunciado: "Señala la oración que contiene un adverbio de NEGACIÓN.", opciones: ["Luis corre", "Nunca miente", "Es blanco", "Ven ahora"], correcta:  1, observaciones: "Nunca niega que la acción pase en algún momento." },
 { id: 117, enunciado: "Señala la oración que contiene un adverbio de NEGACIÓN.", opciones: ["Tampoco sabe", "Es de noche", "Mira esto", "Sube ya"], correcta:  0, observaciones: "Tampoco se usa para negar algo que se suma." },
 { id: 118, enunciado: "Señala la oración que contiene un adverbio de NEGACIÓN.", opciones: ["Es suave", "Jamás falla", "Ponlo allí", "Dame más"], correcta:  1, observaciones: "Jamás es una negación muy fuerte en el tiempo." },
 { id: 119, enunciado: "Señala la oración que contiene un adverbio de NEGACIÓN.", opciones: ["Nada queda", "Es largo", "Mira bien", "Ven pronto"], correcta:  0, observaciones: "Nada niega que exista alguna cantidad." },
 { id: 120, enunciado: "Señala la oración que contiene un adverbio de DUDA.", opciones: ["Es mío", "Acaso viene", "No llores", "Está aquí"], correcta:  1, observaciones: "Acaso indica que no estamos seguros de si vendrá." },
 { id: 121, enunciado: "Señala la oración que contiene un adverbio de DUDA.", opciones: ["Quizá llueva", "Es tarde", "Mira arriba", "Sí, iré"], correcta:  0, observaciones: "Quizá expresa que es posible que pase, pero hay duda." },
 { id: 122, enunciado: "Señala la oración que contiene un adverbio de DUDA.", opciones: ["Es alto", "Tal vez gane", "No hables", "Ponlo ahí"], correcta:  1, observaciones: "Tal vez se usa cuando dudamos si algo ocurrirá." },
 { id: 123, enunciado: "Señala la oración que contiene un adverbio de DUDA.", opciones: ["Igual voy", "Es corto", "Mira esto", "No entres"], correcta:  0, observaciones: "Igual (en lenguaje coloquial) indica una duda o posibilidad." },
 { id: 124, enunciado: "Señala la oración que contiene un adverbio de DUDA.", opciones: ["Posiblemente salga", "Es azul", "Ven ahora", "No mires"], correcta:  0, observaciones: "Posiblemente indica que hay dudas sobre si saldrá." },
 { id: 125, enunciado: "El gato está ___ de la silla.", opciones: ["Debajo", "Mañana", "Bien", "Mucho"], correcta:  0, observaciones: "Debes usar un adverbio de Lugar" },
 { id: 126, enunciado: "___ iré a jugar al parque.", opciones: ["Aquí", "Luego", "Mal", "Poco"], correcta:  1, observaciones: "Debes usar un adverbio de Tiempo" },
 { id: 127, enunciado: "Haz el dibujo ___.", opciones: ["Casi", "Jamás", "Despacio", "Quizá"], correcta:  2, observaciones: "Debes usar un adverbio de Modo" },
 { id: 128, enunciado: "Tengo ___ hambre hoy.", opciones: ["Mucha", "Sí", "Fuera", "Pronto"], correcta:  0, observaciones: "Debes usar un adverbio de Cantidad" },
 { id: 129, enunciado: "___, me gusta el chocolate.", opciones: ["Despacio", "Quizá", "Efectivamente", "Lejos"], correcta:  2, observaciones: "Debes usar un adverbio de Afirmación" },
 { id: 130, enunciado: "Luis ___ llega tarde.", opciones: ["Nunca", "Muy", "Detrás", "Pronto"], correcta:  0, observaciones: "Debes usar un adverbio de Negación" },
 { id: 131, enunciado: "___ vayamos a la playa.", opciones: ["Siempre", "Tal vez", "Nada", "Mal"], correcta:  1, observaciones: "Debes usar un adverbio de Duda" },
 { id: 132, enunciado: "El recreo es ___.", opciones: ["Fuera", "Tal vez", "Mal", "También"], correcta:  0, observaciones: "Debes usar un adverbio de Lugar" },
 { id: 133, enunciado: "___ comí lentejas.", opciones: ["Lejos", "Ayer", "Mal", "Muy"], correcta:  1, observaciones: "Debes usar un adverbio de Tiempo" },
 { id: 134, enunciado: "Luis se porta ___.", opciones: ["Bien", "Quizá", "Cerca", "Mañana"], correcta:  0, observaciones: "Debes usar un adverbio de Modo" },
 { id: 135, enunciado: "Como estaba cansado he dormido ___.", opciones: ["Bastante", "Jamás", "Cerca", "Dificil"], correcta:  0, observaciones: "Debes usar un adverbio de Cantidad" },
 { id: 136, enunciado: "___, yo también quiero.", opciones: ["Tampoco", "Casi", "Sí", "Debajo"], correcta:  2, observaciones: "Debes usar un adverbio de Afirmación" },
 { id: 137, enunciado: "Hoy ___ tengo deberes.", opciones: ["No", "Muy", "Detrás", "Luego"], correcta:  0, observaciones: "Debes usar un adverbio de Negación" },
 { id: 138, enunciado: "___ Luis gane la carrera.", opciones: ["Siempre", "Quizá", "Menos", "Lejos"], correcta:  1, observaciones: "Debes usar un adverbio de Duda" },
 { id: 139, enunciado: "El estuche está ___ del lápiz.", opciones: ["Cerca", "Quizá", "Casi", "También"], correcta:  0, observaciones: "Debes usar un adverbio de Lugar" },
 { id: 140, enunciado: "___ es mi cumpleaños.", opciones: ["Hoy", "Poco", "Claramente", "Seguramente"], correcta:  0, observaciones: "Debes usar un adverbio de Tiempo" },
 { id: 141, enunciado: "Camina  ___ para no caerte.", opciones: ["Nada", "Lejos", "Cuidadosamente", "Todavía"], correcta:  2, observaciones: "Debes usar un adverbio de Modo" },
 { id: 142, enunciado: "Me queda ___ zumo.", opciones: ["Nunca", "Fuera", "Poco", "Mañana"], correcta:  2, observaciones: "Debes usar un adverbio de Cantidad" },
 { id: 143, enunciado: "Luis es ___ inteligente.", opciones: ["Tampoco", "Fuera", "Verdaderamente", "Debajo"], correcta:  2, observaciones: "Debes usar un adverbio de Afirmación" },
 { id: 144, enunciado: "___ quiero brócoli.", opciones: ["Muy", "Detrás", "Tampoco", "Luego"], correcta:  2, observaciones: "Debes usar un adverbio de Negación" },
 { id: 145, enunciado: "___ será mejor esperar.", opciones: ["Quizá", "Menos", "Fácil", "Debajo"], correcta:  2, observaciones: "Debes usar un adverbio de Duda" },
 { id: 146, enunciado: "Luis mira hacia ___.", opciones: ["Mucho", "Hoy", "Arriba", "No"], correcta:  2, observaciones: "Debes usar un adverbio de Lugar" },
 { id: 147, enunciado: "Lavaré los platos ___.", opciones: ["No", "Nada", "Después", "Quizá"], correcta:  2, observaciones: "Debes usar un adverbio de Tiempo" },
 { id: 148, enunciado: "El examen fue ___.", opciones: ["Siempre", "Cerca", "Fácil", "Bastante"], correcta:  2, observaciones: "Debes usar un adverbio de Modo" },
 { id: 149, enunciado: "Quiero comer ___.", opciones: ["Jamás", "Arriba", "Más", "Temprano"], correcta:  2, observaciones: "Debes usar un adverbio de Cantidad" },
 { id: 150, enunciado: "Luis  ___ sabe la lección.", opciones: ["No", "Pronto", "También", "Menos"], correcta:  2, observaciones: "Debes usar un adverbio de Afirmación" },
 { id: 151, enunciado: "No digas ___ a nadie.", opciones: ["Muy", "Fuera", "Nada", "Luego"], correcta:  2, observaciones: "Debes usar un adverbio de Negación" },
 { id: 152, enunciado: "___ vayamos al cine.", opciones: ["Sí", "Deprisa", "Quizá", "Abajo"], correcta:  2, observaciones: "Si usaras DEPRISA necesitaría añadir una coma detrás del adverbio" },
 { id: 153, enunciado: "Guarda el juguete ___.", opciones: ["Poco", "Muy", "Allí", "Quizá"], correcta:  2, observaciones: "Debes usar un adverbio de Lugar" },
 { id: 154, enunciado: "Luis se levantó ___.", opciones: ["Poco", "Claramente", "Temprano", "Cierto"], correcta:  2, observaciones: "Debes usar un adverbio de Tiempo" },
 { id: 155, enunciado: "Luis se peina ___.", opciones: ["Nunca", "Muy", "Así", "Mañana"], correcta:  2, observaciones: "Debes usar un adverbio de Modo" },
 { id: 156, enunciado: "El vaso está ___ lleno.", opciones: ["Sí", "Mañana", "Casi", "Fuera"], correcta:  2, observaciones: "Debes usar un adverbio de Cantidad" },
 { id: 157, enunciado: "Luis vendrá, ___.", opciones: ["Tampoco", "Casi", "Seguramente", "Debajo"], correcta:  2, observaciones: "Debes usar un adverbio de Afirmación" },
 { id: 158, enunciado: "No lo he visto ___.", opciones: ["Muy", "Detrás", "Jamás", "Luego"], correcta:  2, observaciones: "Debes usar un adverbio de Negación" },
 { id: 159, enunciado: "___ apruebe el examen.", opciones: ["Sí", "Mal", "Probablemente", "Lejos"], correcta:  2, observaciones: "Debes usar un adverbio de Duda" },
 { id: 160, enunciado: "El balón está ___.", opciones: ["Pronto", "Bastante", "Ahí", "Seguramente"], correcta:  2, observaciones: "Debes usar un adverbio de Lugar" },
 { id: 161, enunciado: "Luis merienda ___.", opciones: ["Ahora", "Sí", "No", "Muy"], correcta:  0, observaciones: "Debes usar un adverbio de Tiempo" },
 { id: 162, enunciado: "Tengo ___ juguetes.", opciones: ["Muchos", "Jamás", "Mal", "Temprano"], correcta:  0, observaciones: "Debes usar un adverbio de Cantidad" },
 { id: 163, enunciado: "___, ese es mi polo.", opciones: ["Exacto", "Lejos", "Atrás", "Menos"], correcta:  0, observaciones: "Debes usar un adverbio de Afirmación" },
 { id: 164, enunciado: "___ me gusta el ruido.", opciones: ["No", "Muy", "Fuera", "Luego"], correcta:  0, observaciones: "Debes usar un adverbio de Negación" },
 { id: 165, enunciado: "___ nos den un premio.", opciones: ["Posiblemente", "Sí", "Deprisa", "Abajo"], correcta:  0, observaciones: "Debes usar un adverbio de Duda" },
 { id: 166, enunciado: "El perro corre por ___.", opciones: ["Aquí", "Tarde", "Muy", "También"], correcta:  0, observaciones: "Debes usar un adverbio de Lugar" },
 { id: 167, enunciado: "Luis llegará ___.", opciones: ["Poco", "Pronto", "Claramente", "Cierto"], correcta:  1, observaciones: "Debes usar un adverbio de Tiempo" },
 { id: 168, enunciado: "Hazlo ___ como yo.", opciones: ["Nunca", "Igual", "Allí", "Cierto"], correcta:  1, observaciones: "Debes usar un adverbio de Modo" },
 { id: 169, enunciado: "No quiero comer ___.", opciones: ["Sí", "Tanto", "No", "Cierto"], correcta:  1, observaciones: "Debes usar un adverbio de Cantidad" },
 { id: 170, enunciado: "Es ___ verdad lo que dice.", opciones: ["Tampoco", "Ciertamente", "Mañana", "Debajo"], correcta:  1, observaciones: "Debes usar un adverbio de Afirmación" },
 { id: 171, enunciado: "No quiero ir, ___.", opciones: ["Muy", "Tampoco", "Detrás", "Igual"], correcta:  1, observaciones: "Debes usar un adverbio de Negación" },
 { id: 172, enunciado: "___ mañana hará sol.", opciones: ["Mañana", "Seguro", "Mal", "Lejos"], correcta:  1, observaciones: "Debes usar un adverbio de Duda" },
 { id: 173, enunciado: "El patio está ___.", opciones: ["Pronto", "Atrás", "Bastante", "Sí"], correcta:  1, observaciones: "Debes usar un adverbio de Lugar" }


// Puedes seguir añadiendo hasta 50 siguiendo exactamente este formato.
 // RECUERDA: La última pregunta NO debe llevar coma después de su llave de cierre }.
];