var DATOS_BATERIA = [

 { id: 1, enunciado: "Llamamos AFGANO a la persona que ha nacido en:", opciones: ["Kazajistán", "Amonestán", "Afasia", "Afganistán"], correcta:  3, observaciones: "" },
 { id: 2, enunciado: "Llamamos ALEMÁN a la persona que ha nacido en:", opciones: ["Alevosía", "Alemania", "Alimaña", "Armenia"], correcta:  1, observaciones: "" },
 { id: 3, enunciado: "Llamamos ALMERIENSE a la persona que ha nacido en:", opciones: ["Argelia", "Almería", "Almirante", "Alquería"], correcta:  1, observaciones: "" },
 { id: 4, enunciado: "Llamamos ANDALUZA a la persona que ha nacido en:", opciones: ["Andasol", "Dulzura", "Andalucía", "Almería"], correcta:  2, observaciones: "" },
 { id: 5, enunciado: "Llamamos ANDORRANO a la persona que ha nacido en:", opciones: ["Andorra", "Añoranza", "Atolón", "Angora"], correcta:  0, observaciones: "" },
 { id: 6, enunciado: "Llamamos ARGELINO a la persona que ha nacido en:", opciones: ["Alergia", "Argel", "Argelino", "Argelia"], correcta:  3, observaciones: "" },
 { id: 7, enunciado: "Llamamos ARGENTINO a la persona que ha nacido en:", opciones: ["Argentina", "Argentino", "Arpillería", "Atentina"], correcta:  0, observaciones: "" },
 { id: 8, enunciado: "Llamamos ARMENIO a la persona que ha nacido en:", opciones: ["Amonio", "Armonía", "Almería", "Armenia"], correcta:  3, observaciones: "" },
 { id: 9, enunciado: "Llamamos ASTURIANO a la persona que ha nacido en:", opciones: ["Asturias", "Asturión", "Astucia", "Esturias"], correcta:  0, observaciones: "" },
 { id: 10, enunciado: "Llamamos AUSTRALIANO a la persona que ha nacido en:", opciones: ["Austral", "Austero", "Australasia", "Australia"], correcta:  3, observaciones: "" },
 { id: 11, enunciado: "Llamamos AUSTRIACO a la persona que ha nacido en:", opciones: ["Autista", "Astucia", "Austria", "Austro"], correcta:  2, observaciones: "" },
 { id: 12, enunciado: "Llamamos BARCELONÉS a la persona que ha nacido en:", opciones: ["Barcelona", "Barcaza", "Barceloneta", "Barceló"], correcta:  0, observaciones: "" },
 { id: 13, enunciado: "Llamamos BELGA a la persona que ha nacido en:", opciones: ["Bélico", "Báltico", "Belga", "Bélgica"], correcta:  3, observaciones: "" },
 { id: 14, enunciado: "Llamamos BIELORRUSO a la persona que ha nacido en:", opciones: ["Bielorrusia", "Bioluminiscencia", "Borrusia", "Rusia"], correcta:  0, observaciones: "" },
 { id: 15, enunciado: "Llamamos BILBAÍNO a la persona que ha nacido en:", opciones: ["Bambú", "Balboa", "Bivalvo", "Bilbao"], correcta:  3, observaciones: "" },
 { id: 16, enunciado: "Llamamos BOLIVIANO a la persona que ha nacido en:", opciones: ["Bolivariano", "Bolo", "Bolivia", "Bolillo"], correcta:  2, observaciones: "" },
 { id: 17, enunciado: "Llamamos BOSNIO a la persona que ha nacido en:", opciones: ["Bosnia y Herzegovina", "Boina", "Herencia", "Bosnolandia"], correcta:  0, observaciones: "" },
 { id: 18, enunciado: "Llamamos BRASILEÑO a la persona que ha nacido en:", opciones: ["Brasilia", "Brasil", "Brasas", "Brasero"], correcta:  1, observaciones: "" },
 { id: 19, enunciado: "Llamamos BRITÁNICO a la persona que ha nacido en:", opciones: ["Renovado", "Reino Unido", "Reunido", "Reunión"], correcta:  1, observaciones: "" },
 { id: 20, enunciado: "Llamamos BURGALÉS a la persona que ha nacido en:", opciones: ["Bulgaria", "Vulgar", "Burgo", "Burgos"], correcta:  3, observaciones: "" },
 { id: 21, enunciado: "Llamamos CANADIENSE a la persona que ha nacido en:", opciones: ["Cañada", "Canalla", "Cánada", "Canadá"], correcta:  3, observaciones: "" },
 { id: 22, enunciado: "Llamamos CANARIO a la persona que ha nacido en:", opciones: ["Canódromo", "Islas Canarias", "Canario", "Canas"], correcta:  1, observaciones: "" },
 { id: 23, enunciado: "Llamamos CÁNTABRO a la persona que ha nacido en:", opciones: ["Cantimplora", "Calabria", "Cantabria", "Cantante"], correcta:  2, observaciones: "" },
 { id: 24, enunciado: "Llamamos CEUTÍ a la persona que ha nacido en:", opciones: ["Cebra", "Cauta", "Celda", "Ceuta"], correcta:  3, observaciones: "" },
 { id: 25, enunciado: "Llamamos CHECO a la persona que ha nacido en:", opciones: ["República Checa", "Acecho", "Chequera", "Chueca"], correcta:  0, observaciones: "" },
 { id: 26, enunciado: "Llamamos CHILENO a la persona que ha nacido en:", opciones: ["Chicle", "Chire", "Chile", "Chiste"], correcta:  2, observaciones: "" },
 { id: 27, enunciado: "Llamamos CHINO a la persona que ha nacido en:", opciones: ["Quina", "China", "Chinche", "Cincha"], correcta:  1, observaciones: "" },
 { id: 28, enunciado: "Llamamos CHIPRIOTA a la persona que ha nacido en:", opciones: ["Chipre", "Ciprés", "Cobre", "Churre"], correcta:  0, observaciones: "" },
 { id: 29, enunciado: "Llamamos COLOMBIANO a la persona que ha nacido en:", opciones: ["Columpio", "Colombo", "Colombia", "Columna"], correcta:  2, observaciones: "" },
 { id: 30, enunciado: "Llamamos CORDOBÉS a la persona que ha nacido en:", opciones: ["Codorniz", "Córdoba", "Cordura", "Cordobés"], correcta:  1, observaciones: "" },
 { id: 31, enunciado: "Llamamos COREANO a la persona que ha nacido en:", opciones: ["Corista", "Corea del Sur", "Coraza", "Correa"], correcta:  1, observaciones: "" },
 { id: 32, enunciado: "Llamamos CORUÑÉS a la persona que ha nacido en:", opciones: ["La Coruña", "Coruñés", "Corona", "Colmena"], correcta:  0, observaciones: "" },
 { id: 33, enunciado: "Llamamos COSTARRICENSE a la persona que ha nacido en:", opciones: ["Costa", "Ricarica", "Costa Rica", "Costra"], correcta:  2, observaciones: "" },
 { id: 34, enunciado: "Llamamos CROATA a la persona que ha nacido en:", opciones: ["Croata", "Cloaca", "Cruasán", "Croacia"], correcta:  3, observaciones: "" },
 { id: 35, enunciado: "Llamamos CUBANO a la persona que ha nacido en:", opciones: ["Cubo", "Cuba", "Cubeta", "Cuna"], correcta:  1, observaciones: "" },
 { id: 36, enunciado: "Llamamos DANÉS a la persona que ha nacido en:", opciones: ["Dinamarca", "Dime", "Dinámico", "Dinamo"], correcta:  0, observaciones: "" },
 { id: 37, enunciado: "Llamamos DOMINICANO a la persona que ha nacido en:", opciones: ["República Dominicana", "Dominante", "Domino", "Domínico"], correcta:  0, observaciones: "" },
 { id: 38, enunciado: "Llamamos ECUATORIANO a la persona que ha nacido en:", opciones: ["Eucalipto", "Ecuánime", "Ecuador", "Ecuación"], correcta:  2, observaciones: "" },
 { id: 39, enunciado: "Llamamos EGIPCIO a la persona que ha nacido en:", opciones: ["Egipcio", "Edicto", "Elipse", "Egipto"], correcta:  3, observaciones: "" },
 { id: 40, enunciado: "Llamamos ESCOCÉS a la persona que ha nacido en:", opciones: ["Escote", "Esencia", "Escocia", "Escoria"], correcta:  2, observaciones: "" },
 { id: 41, enunciado: "Llamamos ESLOVACO a la persona que ha nacido en:", opciones: ["Eslovenia", "Eslovaco", "Eslora", "Eslovaquia"], correcta:  3, observaciones: "" },
 { id: 42, enunciado: "Llamamos ESLOVENO a la persona que ha nacido en:", opciones: ["Eslovenia", "Eslovaquia", "Esloveno", "Eslogan"], correcta:  0, observaciones: "" },
 { id: 43, enunciado: "Llamamos ESPAÑOL a la persona que ha nacido en:", opciones: ["Españía", "Empeño", "España", "Espada"], correcta:  2, observaciones: "" },
 { id: 44, enunciado: "Llamamos ESTADOUNIDENSE a la persona que ha nacido en:", opciones: ["Estadista", "Estado", "Estados Unidos", "Estadillos"], correcta:  2, observaciones: "" },
 { id: 45, enunciado: "Llamamos ESTONIO a la persona que ha nacido en:", opciones: ["Estantería", "Estonio", "Estonia", "Estonio"], correcta:  2, observaciones: "" },
 { id: 46, enunciado: "Llamamos FILIPINO a la persona que ha nacido en:", opciones: ["Filipinas", "Filminas", "Filípica", "Filis"], correcta:  0, observaciones: "" },
 { id: 47, enunciado: "Llamamos FINLANDÉS a la persona que ha nacido en:", opciones: ["Islandia", "Finlandia", "Filandia", "Finura"], correcta:  1, observaciones: "" },
 { id: 48, enunciado: "Llamamos FRANCÉS a la persona que ha nacido en:", opciones: ["Franco", "Francio", "Francia", "Franja"], correcta:  2, observaciones: "" },
 { id: 49, enunciado: "Llamamos GADITANO a la persona que ha nacido en:", opciones: ["Cáliz", "Matiz", "Cadice", "Cádiz"], correcta:  3, observaciones: "" },
 { id: 50, enunciado: "Llamamos GALÉS a la persona que ha nacido en:", opciones: ["Galeno", "Gales", "Ganas", "Galas"], correcta:  1, observaciones: "" },
 { id: 51, enunciado: "Llamamos GALLEGO a la persona que ha nacido en:", opciones: ["Galicia", "Galaxia", "Galicismo", "Milicia"], correcta:  0, observaciones: "" },
 { id: 52, enunciado: "Llamamos GEORGIANO a la persona que ha nacido en:", opciones: ["Georgia", "Georgina", "Geórgico", "Gorgia"], correcta:  0, observaciones: "" },
 { id: 53, enunciado: "Llamamos GOMERO a la persona que ha nacido en:", opciones: ["Gomera", "La Gomera", "Gominola", "Goma"], correcta:  1, observaciones: "" },
 { id: 54, enunciado: "Llamamos GRANADINO a la persona que ha nacido en:", opciones: ["Granadina", "Granada", "Granate", "Granado"], correcta:  1, observaciones: "" },
 { id: 55, enunciado: "Llamamos GRIEGO a la persona que ha nacido en:", opciones: ["Gracia", "Grecocentro", "Grecia", "Gracia"], correcta:  2, observaciones: "" },
 { id: 56, enunciado: "Llamamos GUATEMALTECO a la persona que ha nacido en:", opciones: ["Guatemala", "Guateque", "Guatepeor", "Guatemalteco"], correcta:  0, observaciones: "" },
 { id: 57, enunciado: "Llamamos HOLANDÉS a la persona que ha nacido en:", opciones: ["Holandés", "Yolanda", "Holanda", "Molienda"], correcta:  2, observaciones: "" },
 { id: 58, enunciado: "Llamamos HONDUREÑO a la persona que ha nacido en:", opciones: ["Honduras", "Hondura", "Cordura", "Hendidura"], correcta:  0, observaciones: "" },
 { id: 59, enunciado: "Llamamos HÚNGARO a la persona que ha nacido en:", opciones: ["Hungría", "Húngaro", "Mugre", "Ungría"], correcta:  0, observaciones: "" },
 { id: 60, enunciado: "Llamamos INDIO a la persona que ha nacido en:", opciones: ["India", "Indio", "Indicio", "Indio"], correcta:  0, observaciones: "" },
 { id: 61, enunciado: "Llamamos INDONESIO a la persona que ha nacido en:", opciones: ["Docencia", "Indonesia", "Indostán", "Indulgencia"], correcta:  1, observaciones: "" },
 { id: 62, enunciado: "Llamamos INGLÉS a la persona que ha nacido en:", opciones: ["Inlaterra", "Inglaterra", "Inmaculada", "Inglés"], correcta:  1, observaciones: "" },
 { id: 63, enunciado: "Llamamos IRANÍ a la persona que ha nacido en:", opciones: ["Imán", "Ira", "Irani", "Irán"], correcta:  3, observaciones: "" },
 { id: 64, enunciado: "Llamamos IRAQUÍ a la persona que ha nacido en:", opciones: ["Iracundo", "Iran", "Irak", "Siroco"], correcta:  2, observaciones: "" },
 { id: 65, enunciado: "Llamamos IRLANDÉS a la persona que ha nacido en:", opciones: ["Islandia", "Irlando", "Hilandera", "Irlanda"], correcta:  3, observaciones: "" },
 { id: 66, enunciado: "Llamamos ISLANDÉS a la persona que ha nacido en:", opciones: ["Islario", "Islanda", "Islandia", "Irlanda"], correcta:  2, observaciones: "" },
 { id: 67, enunciado: "Llamamos ISRAELÍ a la persona que ha nacido en:", opciones: ["Israel", "Isabel", "Israelí", "Israele"], correcta:  0, observaciones: "" },
 { id: 68, enunciado: "Llamamos ITALIANO a la persona que ha nacido en:", opciones: ["Estirar", "Italia", "Italos", "Idilio"], correcta:  1, observaciones: "" },
 { id: 69, enunciado: "Llamamos JAPONÉS a la persona que ha nacido en:", opciones: ["Jampón", "Jabón", "Japonesa", "Japón"], correcta:  3, observaciones: "" },
 { id: 70, enunciado: "Llamamos JIENNENSE a la persona que ha nacido en:", opciones: ["Jaén", "Faén", "Jimena", "Jayán"], correcta:  0, observaciones: "" },
 { id: 71, enunciado: "Llamamos JORDANO a la persona que ha nacido en:", opciones: ["Jordania", "Jordán", "Jardinería", "Jardín"], correcta:  0, observaciones: "" },
 { id: 72, enunciado: "Llamamos LEONÉS a la persona que ha nacido en:", opciones: ["Limón", "León", "Peón", "Leona"], correcta:  1, observaciones: "" },
 { id: 73, enunciado: "Llamamos LETÓN a la persona que ha nacido en:", opciones: ["Lituania", "Letonia", "Letanía", "Lejanía"], correcta:  1, observaciones: "" },
 { id: 74, enunciado: "Llamamos LIBANÉS a la persona que ha nacido en:", opciones: ["Liviano", "Libanés", "Líbano", "Libación"], correcta:  2, observaciones: "" },
 { id: 75, enunciado: "Llamamos LITUANO a la persona que ha nacido en:", opciones: ["Lituania", "Letonia", "Liturgia", "Lima"], correcta:  0, observaciones: "" },
 { id: 76, enunciado: "Llamamos LUCENSE a la persona que ha nacido en:", opciones: ["Lujo", "Ludo", "Luego", "Lugo"], correcta:  3, observaciones: "" },
 { id: 77, enunciado: "Llamamos MACEDONIO a la persona que ha nacido en:", opciones: ["Macadán", "Mecedora", "Macedonio", "Macedonia"], correcta:  3, observaciones: "" },
 { id: 78, enunciado: "Llamamos MADRILEÑO a la persona que ha nacido en:", opciones: ["Madre", "Madrid", "Madriguera", "Madril"], correcta:  1, observaciones: "" },
 { id: 79, enunciado: "Llamamos MALAGUEÑO a la persona que ha nacido en:", opciones: ["Malagueña", "Malva", "Malanga", "Málaga"], correcta:  3, observaciones: "" },
 { id: 80, enunciado: "Llamamos MALAYO a la persona que ha nacido en:", opciones: ["Melaza", "Malasia", "Malo", "Molestia"], correcta:  1, observaciones: "" },
 { id: 81, enunciado: "Llamamos MALTÉS a la persona que ha nacido en:", opciones: ["Malta", "Maltosa", "Malteada", "Malla"], correcta:  0, observaciones: "" },
 { id: 82, enunciado: "Llamamos MARROQUÍ a la persona que ha nacido en:", opciones: ["Marruecos", "Barraca", "Marrueco", "Marro"], correcta:  0, observaciones: "" },
 { id: 83, enunciado: "Llamamos MELILLENSE a la persona que ha nacido en:", opciones: ["Mirilla", "Melilla", "Mecha", "Melaza"], correcta:  1, observaciones: "" },
 { id: 84, enunciado: "Llamamos MEXICANO a la persona que ha nacido en:", opciones: ["Méjico", "Melva", "Mejor", "Místico"], correcta:  0, observaciones: "" },
 { id: 85, enunciado: "Llamamos MONEGASCO a la persona que ha nacido en:", opciones: ["Monarca", "Mona Lisa", "Monóculo", "Mónaco"], correcta:  3, observaciones: "" },
 { id: 86, enunciado: "Llamamos MURCIANO a la persona que ha nacido en:", opciones: ["Murga", "Murciélago", "Murcia", "Muralla"], correcta:  2, observaciones: "" },
 { id: 87, enunciado: "Llamamos NAVARRO a la persona que ha nacido en:", opciones: ["Navarra", "Narra", "Navarro", "Navaja"], correcta:  0, observaciones: "" },
 { id: 88, enunciado: "Llamamos NEERLANDÉS a la persona que ha nacido en:", opciones: ["País", "Paisaje", "Países Bajos", "Pasos"], correcta:  2, observaciones: "" },
 { id: 89, enunciado: "Llamamos NEPALÍ a la persona que ha nacido en:", opciones: ["Nopal", "Napal", "Nepal", "Nopal"], correcta:  2, observaciones: "" },
 { id: 90, enunciado: "Llamamos NICARAGÜENSE a la persona que ha nacido en:", opciones: ["Nicotina", "Nicaragüense", "Nicaragua", "Nicanor"], correcta:  2, observaciones: "" },
 { id: 91, enunciado: "Llamamos NIGERIANO a la persona que ha nacido en:", opciones: ["Nilo", "Níveo", "Nigeria", "Níger"], correcta:  2, observaciones: "" },
 { id: 92, enunciado: "Llamamos NORUEGO a la persona que ha nacido en:", opciones: ["Noruego", "Moguer", "Nórdico", "Noruega"], correcta:  3, observaciones: "" },
 { id: 93, enunciado: "Llamamos ONUBENSE a la persona que ha nacido en:", opciones: ["Huelva", "Vuelva", "Huesca", "Huela"], correcta:  0, observaciones: "" },
 { id: 94, enunciado: "Llamamos PALMERO a la persona que ha nacido en:", opciones: ["La Palma", "Palma", "Palmas", "Palmera"], correcta:  0, observaciones: "" },
 { id: 95, enunciado: "Llamamos PANAMEÑO a la persona que ha nacido en:", opciones: ["Panameño", "Panamá", "Pana", "Panes"], correcta:  1, observaciones: "" },
 { id: 96, enunciado: "Llamamos PAQUISTANÍ a la persona que ha nacido en:", opciones: ["Paquistaní", "Pakistán", "Afganistán", "Kurdistán"], correcta:  1, observaciones: "" },
 { id: 97, enunciado: "Llamamos PARAGUAYO a la persona que ha nacido en:", opciones: ["Paragüero", "Paraguay", "Nectarina", "Paraguas"], correcta:  1, observaciones: "" },
 { id: 98, enunciado: "Llamamos PERUANO a la persona que ha nacido en:", opciones: ["Perilla", "Pera", "Perusa", "Perú"], correcta:  3, observaciones: "" },
 { id: 99, enunciado: "Llamamos POLACO a la persona que ha nacido en:", opciones: ["Colonia", "Polo", "Polonio", "Polonia"], correcta:  3, observaciones: "" },
 { id: 100, enunciado: "Llamamos PONTEVEDRÉS a la persona que ha nacido en:", opciones: ["Puntero", "Puente", "Pontevedra", "Ponte"], correcta:  2, observaciones: "" },
 { id: 101, enunciado: "Llamamos PORTUGUÉS a la persona que ha nacido en:", opciones: ["Portu", "Portugalete", "Portugués", "Portugal"], correcta:  3, observaciones: "" },
 { id: 102, enunciado: "Llamamos RIOJANO a la persona que ha nacido en:", opciones: ["Rioja", "La Rioja", "Rioja", "Roja"], correcta:  1, observaciones: "" },
 { id: 103, enunciado: "Llamamos RUMANO a la persona que ha nacido en:", opciones: ["Roma", "Romano", "Rumanía", "Romana"], correcta:  2, observaciones: "" },
 { id: 104, enunciado: "Llamamos RUSO a la persona que ha nacido en:", opciones: ["Rosado", "Rusia", "Rusa", "Ruso"], correcta:  1, observaciones: "" },
 { id: 105, enunciado: "Llamamos SALMANTINO a la persona que ha nacido en:", opciones: ["Salmón", "Salamanquino", "Salamanca", "Salamandra"], correcta:  2, observaciones: "" },
 { id: 106, enunciado: "Llamamos SALVADOREÑO a la persona que ha nacido en:", opciones: ["El Salvador", "Salvador", "Salva", "Salvador"], correcta:  0, observaciones: "" },
 { id: 107, enunciado: "Llamamos SERBIO a la persona que ha nacido en:", opciones: ["Serbia", "Sober", "Sorbia", "Sorbio"], correcta:  0, observaciones: "" },
 { id: 108, enunciado: "Llamamos SEVILLANO a la persona que ha nacido en:", opciones: ["Sevilla", "Villano", "Sevillana", "Semilla"], correcta:  0, observaciones: "" },
 { id: 109, enunciado: "Llamamos SIRIO a la persona que ha nacido en:", opciones: ["Siria", "Siracusa", "Sima", "Silice"], correcta:  0, observaciones: "" },
 { id: 110, enunciado: "Llamamos SUDAFRICANO a la persona que ha nacido en:", opciones: ["Sur", "África", "Sudafricano", "Sudáfrica"], correcta:  3, observaciones: "" },
 { id: 111, enunciado: "Llamamos SUECO a la persona que ha nacido en:", opciones: ["Sueco", "Suiza", "Suecia", "Sucio"], correcta:  2, observaciones: "" },
 { id: 112, enunciado: "Llamamos SUIZO a la persona que ha nacido en:", opciones: ["Suiza", "Socio", "Suizo", "Suecia"], correcta:  0, observaciones: "" },
 { id: 113, enunciado: "Llamamos TAILANDÉS a la persona que ha nacido en:", opciones: ["Tanzania", "Tai", "Tasmania", "Tailandia"], correcta:  3, observaciones: "" },
 { id: 114, enunciado: "Llamamos PORTUENSE a la persona que ha nacido en:", opciones: ["Oporto", "Portimao", "El Puerto de Santa María", "Portillo"], correcta:  2, observaciones: "" },
 { id: 115, enunciado: "Llamamos TINERFEÑO a la persona que ha nacido en:", opciones: ["Tener", "Teneré", "Tenerife", "Tener"], correcta:  2, observaciones: "" },
 { id: 116, enunciado: "Llamamos TOLEDANO a la persona que ha nacido en:", opciones: ["Torero", "Toldo", "Toldo", "Toledo"], correcta:  3, observaciones: "" },
 { id: 117, enunciado: "Llamamos TUNECINO a la persona que ha nacido en:", opciones: ["Turco", "Túnez", "Teñir", "Túnica"], correcta:  1, observaciones: "" },
 { id: 118, enunciado: "Llamamos TURCO a la persona que ha nacido en:", opciones: ["Tuerca", "Turquía", "Torcer", "Turco"], correcta:  1, observaciones: "" },
 { id: 119, enunciado: "Llamamos UCRANIANO a la persona que ha nacido en:", opciones: ["Ucranio", "Craneo", "Ucrania", "Lucrecia"], correcta:  2, observaciones: "" },
 { id: 120, enunciado: "Llamamos URUGUAYO a la persona que ha nacido en:", opciones: ["Urogallo", "Uruguay", "Gallo", "Paraguay"], correcta:  1, observaciones: "" },
 { id: 121, enunciado: "Llamamos VALENCIANO a la persona que ha nacido en:", opciones: ["Venecia", "Valencia", "Valer", "Valenciano"], correcta:  1, observaciones: "" },
 { id: 122, enunciado: "Llamamos VASCO a la persona que ha nacido en:", opciones: ["País Vasco", "Vasco", "Vasca", "Vascuence"], correcta:  0, observaciones: "" },
 { id: 123, enunciado: "Llamamos VENEZOLANO a la persona que ha nacido en:", opciones: ["Valenzuela", "Venezolana", "Venir", "Venezuela"], correcta:  3, observaciones: "" },
 { id: 124, enunciado: "Llamamos VIETNAMITA a la persona que ha nacido en:", opciones: ["Vietnam", "Viene", "Vietnamitas", "Vendrán"], correcta:  0, observaciones: "" },
 { id: 125, enunciado: "Llamamos ZARAGOZANO a la persona que ha nacido en:", opciones: ["Zamora", "Zarzalejo", "Zaragoza", "Zaragocista"], correcta:  2, observaciones: "" },
 { id: 126, enunciado: "El natural de BOSNIA Y HERZEGOVINA se llama:", opciones: ["Boina", "Barniz", "Bocio", "Bosnio"], correcta:  3, observaciones: "" },
 { id: 127, enunciado: "El natural de NIGERIA se llama:", opciones: ["Nigero", "Níveo", "Nigeriano", "Níger"], correcta:  2, observaciones: "" },
 { id: 128, enunciado: "El natural de PAÍSES BAJOS se llama:", opciones: ["Tailandés", "Neerlandés", "Islandés", "Paisano"], correcta:  1, observaciones: "" },
 { id: 129, enunciado: "El natural de LA GOMERA se llama:", opciones: ["Gomera", "Gomero", "Romero", "Gominola"], correcta:  1, observaciones: "" },
 { id: 130, enunciado: "El natural de POLONIA se llama:", opciones: ["Polaco", "Polonia", "Polca", "Polonio"], correcta:  0, observaciones: "" },
 { id: 131, enunciado: "El natural de UCRANIA se llama:", opciones: ["Craneo", "Ruso", "Úrsula", "Ucraniano"], correcta:  3, observaciones: "" },
 { id: 132, enunciado: "El natural de MARRUECOS se llama:", opciones: ["Marroquinería", "Marroco", "Macarrón", "Marroquí"], correcta:  3, observaciones: "" },
 { id: 133, enunciado: "El natural de EL SALVADOR se llama:", opciones: ["Salvador", "Salvadoreño", "Salvo", "Salvado"], correcta:  1, observaciones: "" },
 { id: 134, enunciado: "El natural de BURGOS se llama:", opciones: ["Bordelés", "Burgalés", "Burgués", "Buriel"], correcta:  1, observaciones: "" },
 { id: 135, enunciado: "El natural de CEUTA se llama:", opciones: ["Curtí", "Ceutí", "Cauto", "Ceuto"], correcta:  1, observaciones: "" },
 { id: 136, enunciado: "El natural de ARGELIA se llama:", opciones: ["Argel", "Argelino", "Argelio", "Angelino"], correcta:  1, observaciones: "" },
 { id: 137, enunciado: "El natural de ANDALUCÍA se llama:", opciones: ["Andaluza", "Altramuz", "Andanza", "Ataluza"], correcta:  0, observaciones: "" },
 { id: 138, enunciado: "El natural de PAKISTÁN se llama:", opciones: ["Paquistaní", "Paco", "Paqui", "Pasquín"], correcta:  0, observaciones: "" },
 { id: 139, enunciado: "El natural de INGLATERRA se llama:", opciones: ["Inglés", "Ingle", "Idólatra", "Ingerir"], correcta:  0, observaciones: "" },
 { id: 140, enunciado: "El natural de BRASIL se llama:", opciones: ["Brasileño", "Brasero", "Brasilete", "Bracilero"], correcta:  0, observaciones: "" },
 { id: 141, enunciado: "El natural de LUGO se llama:", opciones: ["Lucente", "Lugarteniente", "Licencia", "Lucense"], correcta:  3, observaciones: "" },
 { id: 142, enunciado: "El natural de MÓNACO se llama:", opciones: ["Mónaco", "Monico", "Monástico", "Monegasco"], correcta:  3, observaciones: "" },
 { id: 143, enunciado: "El natural de FILIPINAS se llama:", opciones: ["Filípica", "Filio", "Filis", "Filipino"], correcta:  3, observaciones: "" },
 { id: 144, enunciado: "El natural de ISLAS CANARIAS se llama:", opciones: ["Canario", "Can", "Plátano", "Calvario"], correcta:  0, observaciones: "" },
 { id: 145, enunciado: "El natural de GRANADA se llama:", opciones: ["Granadina", "Gradino", "Granadino", "Granate"], correcta:  2, observaciones: "" },
 { id: 146, enunciado: "El natural de ESTADOS UNIDOS se llama:", opciones: ["Estoniense", "Estadista", "Estadounidense", "Estudiantil"], correcta:  2, observaciones: "" },
 { id: 147, enunciado: "El natural de MELILLA se llama:", opciones: ["Mirilla", "Milicense", "Melillense", "Mellizo"], correcta:  2, observaciones: "" },
 { id: 148, enunciado: "El natural de SEVILLA se llama:", opciones: ["Sumidero", "Semillero", "Sevillano", "Villano"], correcta:  2, observaciones: "" },
 { id: 149, enunciado: "El natural de ASTURIAS se llama:", opciones: ["Asturión", "Esturión", "Actuario", "Asturiano"], correcta:  3, observaciones: "" },
 { id: 150, enunciado: "El natural de INDIA se llama:", opciones: ["Idilio", "Indio", "Indiano", "Indicio"], correcta:  1, observaciones: "" },
 { id: 151, enunciado: "El natural de BIELORRUSIA se llama:", opciones: ["Bielorruso", "Borruso", "Ruso", "Bielgo"], correcta:  0, observaciones: "" },
 { id: 152, enunciado: "El natural de MÉJICO se llama:", opciones: ["Méjico", "Mejor", "Mejicano", "Mexcalina"], correcta:  2, observaciones: "" },
 { id: 153, enunciado: "El natural de ESLOVENIA se llama:", opciones: ["Escoba", "Esloveno", "Eslovaco", "Eslogan"], correcta:  1, observaciones: "" },
 { id: 154, enunciado: "El natural de SUECIA se llama:", opciones: ["Suizo", "Zueco", "Sueco", "Sucio"], correcta:  2, observaciones: "" },
 { id: 155, enunciado: "El natural de JAPÓN se llama:", opciones: ["Japonés", "Jabón", "Japo", "Tapon"], correcta:  0, observaciones: "" },
 { id: 156, enunciado: "El natural de San Fernando se llama:", opciones: ["Fernando", "Fernandel", "Fernandino", "Isleño"], correcta:  3, observaciones: "" },
 { id: 157, enunciado: "El natural de PERÚ se llama:", opciones: ["Perulero", "Perusa", "Peruano", "Perilla"], correcta:  2, observaciones: "" },
 { id: 158, enunciado: "El natural de PONTEVEDRA se llama:", opciones: ["Pontero", "Pontonero", "Pontevedrés", "Puente"], correcta:  2, observaciones: "" },
 { id: 159, enunciado: "El natural de AFGANISTÁN se llama:", opciones: ["Órgano", "Afonía", "Afgano", "Arcano"], correcta:  2, observaciones: "" },
 { id: 160, enunciado: "El natural de CHILE se llama:", opciones: ["Chilero", "Chileno", "Chilena", "Relleno"], correcta:  1, observaciones: "" },
 { id: 161, enunciado: "El natural de ESTONIA se llama:", opciones: ["Entonamiento", "Estonio", "Estos", "Estenosis"], correcta:  1, observaciones: "" },
 { id: 162, enunciado: "El natural de FINLANDIA se llama:", opciones: ["Finlandés", "Finito", "Islandés", "Irlandés"], correcta:  0, observaciones: "" },
 { id: 163, enunciado: "El natural de NAVARRA se llama:", opciones: ["Navajero", "Navarro", "Panplonés", "Navarrete"], correcta:  1, observaciones: "" },
 { id: 164, enunciado: "El natural de ALEMANIA se llama:", opciones: ["Alemánide", "Alemán", "Ademán", "Alán"], correcta:  1, observaciones: "" },
 { id: 165, enunciado: "El natural de MALASIA se llama:", opciones: ["Mayo", "Malayo", "Malo", "Maya"], correcta:  1, observaciones: "" },
 { id: 166, enunciado: "El natural de EGIPTO se llama:", opciones: ["Eclipse", "Egipcio", "Edicto", "Elipse"], correcta:  1, observaciones: "" },
 { id: 167, enunciado: "El natural de GALES se llama:", opciones: ["Garcés", "Gaseoso", "Galés", "Galeno"], correcta:  2, observaciones: "" },
 { id: 168, enunciado: "El natural de ISLANDIA se llama:", opciones: ["Isleño", "Islario", "Islandés", "Irlandés"], correcta:  2, observaciones: "" },
 { id: 169, enunciado: "El natural de LEÓN se llama:", opciones: ["Peón", "Leonesa", "Leonés", "Leona"], correcta:  2, observaciones: "" },
 { id: 170, enunciado: "El natural de TÚNEZ se llama:", opciones: ["Tuerca", "Túnica", "Túnico", "Tunecino"], correcta:  3, observaciones: "" },
 { id: 171, enunciado: "El natural de ESCOCIA se llama:", opciones: ["Escozar", "Escocés", "Escozor", "Escoba"], correcta:  1, observaciones: "" },
 { id: 172, enunciado: "El natural de REPÚBLICA DOMINICANA se llama:", opciones: ["Dominante", "Domínico", "Dominante", "Dominicano"], correcta:  3, observaciones: "" },
 { id: 173, enunciado: "El natural de CANADÁ se llama:", opciones: ["Canaense", "Canadiense", "Cañadense", "Canariense"], correcta:  1, observaciones: "" },
 { id: 174, enunciado: "El natural de RUMANÍA se llama:", opciones: ["Maniaco", "Romano", "Húngaro", "Rumano"], correcta:  3, observaciones: "" },
 { id: 175, enunciado: "El natural de SERBIA se llama:", opciones: ["Sorbio", "Serbio", "Soberbio", "Sorbio"], correcta:  1, observaciones: "" },
 { id: 176, enunciado: "El natural de MURCIA se llama:", opciones: ["Murciélago", "Murciano", "Murga", "Marciano"], correcta:  1, observaciones: "" },
 { id: 177, enunciado: "El natural de ZARAGOZA se llama:", opciones: ["Zaragozano", "Zaragocista", "Zamorano", "Zaragozano"], correcta:  0, observaciones: "" },
 { id: 178, enunciado: "El natural de PANAMÁ se llama:", opciones: ["Panameño", "Pana", "Maná", "Panocho"], correcta:  0, observaciones: "" },
 { id: 179, enunciado: "El natural de URUGUAY se llama:", opciones: ["Uruguay", "Uruguayo", "Urogallo", "Urón"], correcta:  1, observaciones: "" },
 { id: 180, enunciado: "El natural de HONDURAS se llama:", opciones: ["Hondureño", "Hondura", "Hondonada", "Hondo"], correcta:  0, observaciones: "" },
 { id: 181, enunciado: "El natural de SALAMANCA se llama:", opciones: ["Salmantino", "Salmón", "Salamanca", "Salamandra"], correcta:  0, observaciones: "" },
 { id: 182, enunciado: "El natural de GUATEMALA se llama:", opciones: ["Guateque", "Mate", "Maltrecho", "Guatemalteco"], correcta:  3, observaciones: "" },
 { id: 183, enunciado: "El natural de LA RIOJA se llama:", opciones: ["Logroñés", "Roano", "Riojo", "Riojano"], correcta:  3, observaciones: "" },
 { id: 184, enunciado: "El natural de INDONESIA se llama:", opciones: ["Docente", "Indonesio", "Indostánico", "Indulgencia"], correcta:  1, observaciones: "" },
 { id: 185, enunciado: "El natural de BILBAO se llama:", opciones: ["Bilbaíno", "Baldaquino", "Albahaca", "Bambino"], correcta:  0, observaciones: "" },
 { id: 186, enunciado: "El natural de MÁLAGA se llama:", opciones: ["Maltrecho", "Malagueño", "Malage", "Malta"], correcta:  1, observaciones: "" },
 { id: 187, enunciado: "El natural de CUBA se llama:", opciones: ["Cunero", "Cupero", "Cubano", "Cubo"], correcta:  2, observaciones: "" },
 { id: 188, enunciado: "El natural de IRAK se llama:", opciones: ["Iracundo", "Iraní", "Iraquí", "Iridio"], correcta:  2, observaciones: "" },
 { id: 189, enunciado: "El natural de LITUANIA se llama:", opciones: ["Letargia", "Liturgia", "Letoniano", "Lituano"], correcta:  3, observaciones: "" },
 { id: 190, enunciado: "El natural de HOLANDA se llama:", opciones: ["Holandés", "Hondanada", "Bolandés", "Holando"], correcta:  0, observaciones: "" },
 { id: 191, enunciado: "El natural de LETONIA se llama:", opciones: ["Lento", "Letón", "Latón", "Letanía"], correcta:  1, observaciones: "" },
 { id: 192, enunciado: "El natural de LA PALMA se llama:", opciones: ["Pampero", "Palmeto", "Palmero", "Palmito"], correcta:  2, observaciones: "" },
 { id: 193, enunciado: "El natural de ALMERÍA se llama:", opciones: ["Ateniense", "Almirante", "Almeriense", "Almeriar"], correcta:  2, observaciones: "" },
 { id: 194, enunciado: "El natural de BOLIVIA se llama:", opciones: ["Bolivariano", "Volviano", "Balonciano", "Boliviano"], correcta:  3, observaciones: "" },
 { id: 195, enunciado: "El natural de FRANCIA se llama:", opciones: ["Franja", "Franja", "Francés", "Frasco"], correcta:  2, observaciones: "" },
 { id: 196, enunciado: "El natural de AUSTRALIA se llama:", opciones: ["Austral", "Australino", "Austero", "Australiano"], correcta:  3, observaciones: "" },
 { id: 197, enunciado: "El natural de CÁDIZ se llama:", opciones: ["Gitano", "Gravitatorio", "Galitano", "Gaditano"], correcta:  3, observaciones: "" },
 { id: 198, enunciado: "El natural de LÍBANO se llama:", opciones: ["Limón", "Libanesa", "Libanés", "Libación"], correcta:  2, observaciones: "" },
 { id: 199, enunciado: "El natural de COREA DEL SUR se llama:", opciones: ["Coraza", "Coriano", "Coreógrafo", "Coreano"], correcta:  3, observaciones: "" },
 { id: 200, enunciado: "El natural de CANTABRIA se llama:", opciones: ["Cántabro", "Cántaro", "Cantar", "Macabro"], correcta:  0, observaciones: "" },
 { id: 201, enunciado: "El natural de JAÉN se llama:", opciones: ["Jimena", "Jayán", "Jiennense", "Jaenero"], correcta:  2, observaciones: "" },
 { id: 202, enunciado: "El natural de MALTA se llama:", opciones: ["Malteado", "Cortés", "Mortés", "Maltés"], correcta:  3, observaciones: "" },
 { id: 203, enunciado: "El natural de REPÚBLICA CHECA se llama:", opciones: ["Chico", "Acecho", "Checo", "Chueco"], correcta:  2, observaciones: "" },
 { id: 204, enunciado: "El natural de VALENCIA se llama:", opciones: ["Valerio", "Valencia", "Valenciano", "Valeno"], correcta:  2, observaciones: "" },
 { id: 205, enunciado: "El natural de VIETNAM se llama:", opciones: ["Vietnamita", "Viento", "Vital", "Vida"], correcta:  0, observaciones: "" },
 { id: 206, enunciado: "El natural de GEORGIA se llama:", opciones: ["Georgiano", "Georgina", "Gregor", "Gorgonio"], correcta:  0, observaciones: "" },
 { id: 207, enunciado: "El natural de ISRAEL se llama:", opciones: ["Israelí", "Moro", "Ismael", "Israele"], correcta:  0, observaciones: "" },
 { id: 208, enunciado: "El natural de COSTA RICA se llama:", opciones: ["Costreñir", "Costarricense", "Costeño", "Ricense"], correcta:  1, observaciones: "" },
 { id: 209, enunciado: "El natural de TURQUÍA se llama:", opciones: ["Duquesa", "Turco", "Turquesa", "Truco"], correcta:  1, observaciones: "" },
 { id: 210, enunciado: "El natural de REINO UNIDO se llama:", opciones: ["Botánico", "Britano", "Bitácora", "Británico"], correcta:  3, observaciones: "" },
 { id: 211, enunciado: "El natural de IRLANDA se llama:", opciones: ["Irlandés", "Islandés", "Iracundo", "Hilandera"], correcta:  0, observaciones: "" },
 { id: 212, enunciado: "El natural de VENEZUELA se llama:", opciones: ["Venecia", "Venezuelo", "Venezolano", "Venencia"], correcta:  2, observaciones: "" },
 { id: 213, enunciado: "El natural de SIRIA se llama:", opciones: ["Sílice", "Sima", "Sirio", "Siriaco"], correcta:  2, observaciones: "" },
 { id: 214, enunciado: "El natural de BÉLGICA se llama:", opciones: ["Belga", "Bélma", "Boga", "Belesa"], correcta:  0, observaciones: "" },
 { id: 215, enunciado: "El natural de CROACIA se llama:", opciones: ["Cloaca", "Corbeta", "Croata", "Acróbata"], correcta:  2, observaciones: "" },
 { id: 216, enunciado: "El natural de ITALIA se llama:", opciones: ["Romano", "Italos", "Italina", "Italiano"], correcta:  3, observaciones: "" },
 { id: 217, enunciado: "El natural de ESPAÑA se llama:", opciones: ["Espolón", "Españumo", "Español", "Espada"], correcta:  2, observaciones: "" },
 { id: 218, enunciado: "El natural de PARAGUAY se llama:", opciones: ["Paragüero", "Paraguayo", "Parado", "Paraguas"], correcta:  1, observaciones: "" },
 { id: 219, enunciado: "El natural de PORTUGAL se llama:", opciones: ["Portuense", "Portugalete", "Portugués", "Polo"], correcta:  2, observaciones: "" },
 { id: 220, enunciado: "El natural de CÓRDOBA se llama:", opciones: ["Adobés", "Cordobés", "Corduente", "Cordura"], correcta:  1, observaciones: "" },
 { id: 221, enunciado: "El natural de IRÁN se llama:", opciones: ["Iraní", "Voy", "Imán", "Iremos"], correcta:  0, observaciones: "" },
 { id: 222, enunciado: "El natural de SUDÁFRICA se llama:", opciones: ["Subrealista", "Africano", "Sudar", "Sudafricano"], correcta:  3, observaciones: "" },
 { id: 223, enunciado: "El natural de RUSIA se llama:", opciones: ["Rusiano", "Roso", "Ruso", "Moscovita"], correcta:  2, observaciones: "" },
 { id: 224, enunciado: "El natural de TAILANDIA se llama:", opciones: ["Tasmania", "Tarima", "Tai", "Tailandés"], correcta:  3, observaciones: "" },
 { id: 225, enunciado: "El natural de CARTAGENA se llama:", opciones: ["Cartagenero", "Cartero", "Cortegana", "Cartador"], correcta:  0, observaciones: "" },
 { id: 226, enunciado: "El natural de CHIPRE se llama:", opciones: ["Chipriota", "Patriota", "Cipriota", "Idiota"], correcta:  0, observaciones: "" },
 { id: 227, enunciado: "El natural de MADRID se llama:", opciones: ["Madriguera", "Madrileño", "Madriles", "Madridejo"], correcta:  1, observaciones: "" },
 { id: 228, enunciado: "El natural de GALICIA se llama:", opciones: ["Galgo", "Gallito", "Gallocresta", "Gallego"], correcta:  3, observaciones: "" },
 { id: 229, enunciado: "El natural de GRECIA se llama:", opciones: ["Griego", "Greco", "Griegue", "Riego"], correcta:  0, observaciones: "" },
 { id: 230, enunciado: "El natural de NORUEGA se llama:", opciones: ["Noverugo", "Noruego", "Novo", "Norte"], correcta:  1, observaciones: "" },
 { id: 231, enunciado: "El natural de ESLOVAQUIA se llama:", opciones: ["Eslora", "Esloveno", "Eslovaco", "Esclavo"], correcta:  2, observaciones: "" },
 { id: 232, enunciado: "El natural de HUELVA se llama:", opciones: ["Onubense", "Nubense", "Ovetense", "Huelvense"], correcta:  0, observaciones: "" },
 { id: 233, enunciado: "El natural de NICARAGUA se llama:", opciones: ["Nico", "Nicaragüina", "Aragüense", "Nicaragüense"], correcta:  3, observaciones: "" },
 { id: 234, enunciado: "El natural de ARGENTINA se llama:", opciones: ["Arpento", "Argentino", "Argenta", "Argento"], correcta:  1, observaciones: "" },
 { id: 235, enunciado: "El natural de ARMENIA se llama:", opciones: ["Armonio", "Amonio", "Arsenio", "Armenio"], correcta:  3, observaciones: "" },
 { id: 236, enunciado: "El natural de HUNGRÍA se llama:", opciones: ["Hungro", "Hunguerino", "Múngaro", "Húngaro"], correcta:  3, observaciones: "" },
 { id: 237, enunciado: "El natural de COLOMBIA se llama:", opciones: ["Columbo", "Columbino", "Colombo", "Colombiano"], correcta:  3, observaciones: "" },
 { id: 238, enunciado: "El natural de TOLEDO se llama:", opciones: ["Torear", "Teledano", "Toldo", "Toledano"], correcta:  3, observaciones: "" },
 { id: 239, enunciado: "El natural de MACEDONIA se llama:", opciones: ["Macedonio", "Macarena", "Macro", "Macadán"], correcta:  0, observaciones: "" },
 { id: 240, enunciado: "El natural de TENERIFE se llama:", opciones: ["Teñir", "Tener", "Teneré", "Tinerfeño"], correcta:  3, observaciones: "" },
 { id: 241, enunciado: "El natural de ECUADOR se llama:", opciones: ["Ecuatoriano", "Ecuánime", "Ecuación", "Ecuménico"], correcta:  0, observaciones: "" },
 { id: 242, enunciado: "El natural de JORDANIA se llama:", opciones: ["Jordán", "Jardinería", "Jordano", "Jordanar"], correcta:  2, observaciones: "" },
 { id: 243, enunciado: "El natural de LA CORUÑA se llama:", opciones: ["Vicuña", "Comúnmente", "Coronel", "Coruñés"], correcta:  3, observaciones: "" },
 { id: 244, enunciado: "El natural de DINAMARCA se llama:", opciones: ["Dinamo", "Danés", "Dianés", "Arnés"], correcta:  1, observaciones: "" },
 { id: 245, enunciado: "El natural de BARCELONA se llama:", opciones: ["Barcelona", "Barzonés", "Barcelonés", "Barloventés"], correcta:  2, observaciones: "" },
 { id: 246, enunciado: "El natural de SUIZA se llama:", opciones: ["Sizo", "Suizo", "Sucio", "Sueco"], correcta:  1, observaciones: "" },
 { id: 247, enunciado: "El natural de NEPAL se llama:", opciones: ["Nepotismo", "Nopal", "Nepote", "Nepalí"], correcta:  3, observaciones: "" },
 { id: 248, enunciado: "El natural de ANDORRA se llama:", opciones: ["Andurriana", "Andorrano", "Alcorano", "Añoranza"], correcta:  1, observaciones: "" },
 { id: 249, enunciado: "El natural de CHINA se llama:", opciones: ["Chile", "Chino", "Chinche", "Cincha"], correcta:  1, observaciones: "" },
 { id: 250, enunciado: "El natural de AUSTRIA se llama:", opciones: ["Austriaco", "Astronauta", "Autista", "Austero"], correcta:  0, observaciones: "" }


// Puedes seguir añadiendo hasta 50 siguiendo exactamente este formato.
 // RECUERDA: La última pregunta NO debe llevar coma después de su llave de cierre }.
];
