var DATOS_BATERIA = [


 { id: 1, enunciado: "La hormiga es pequeña.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 2, enunciado: "El desierto es tan seco como el polvo.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 3, enunciado: "Una casa es más espaciosa que un piso.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 4, enunciado: "La llanura es menos empinada que la cuesta.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 5, enunciado: "Mi cama es más blanda que el suelo.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 6, enunciado: "Mi hermano es tan travieso como yo.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 7, enunciado: "El niño es bajo.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 8, enunciado: "Mi mochila es tan pesada como la de Luis.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 9, enunciado: "El papel es menos duro que la madera.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Superlativo", "Positivo"], correcta:  1, observaciones: "" },
 { id: 10, enunciado: "Mi madre es la más guapa de la fiesta.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 11, enunciado: "Un charco es menos hondo que el mar.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  2, observaciones: "" },
 { id: 12, enunciado: "El zumo es tan rico como la leche.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 13, enunciado: "El río es ancho.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 14, enunciado: "Leer es más interesante que ver la tele.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 15, enunciado: "La jirafa es más alta que el elefante.", opciones: ["Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 16, enunciado: "Este ejercicio es menos difícil que aquel.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 17, enunciado: "El sol es más grande que la tierra.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 18, enunciado: "Mi amigo es bueno.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 19, enunciado: "La liebre es más veloz que la tortuga.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 20, enunciado: "El agua está tan clara como el cristal.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 21, enunciado: "Es el desierto más seco del planeta.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 22, enunciado: "Es el día más feliz de mi vida.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 23, enunciado: "La ciudad es más ruidosa que el campo.", opciones: ["Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 24, enunciado: "La leche está fría.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 25, enunciado: "La calle está ruidosísima.", opciones: ["Superlativo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 26, enunciado: "La tarde está calurosísima.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 27, enunciado: "La nieve es fría.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 28, enunciado: "El camino es tan pedregoso como el río.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 29, enunciado: "La montaña es más alta que la colina.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 30, enunciado: "El peluche es tierno.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 31, enunciado: "La fresa es menos ácida que el limón.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 32, enunciado: "El payaso es graciosísimo.", opciones: ["Superlativo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 33, enunciado: "La manzana es roja.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 34, enunciado: "El invierno es frío.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 35, enunciado: "El oso es peludo.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 36, enunciado: "El edificio es modernísimo.", opciones: ["Superlativo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 37, enunciado: "El volcán es más peligroso que el lago.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 38, enunciado: "Mi amigo es simpatiquísimo.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 39, enunciado: "El queso es sabroso.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 40, enunciado: "El metal es tan duro como la roca.", opciones: ["Comparativo de Superioridad", "Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 41, enunciado: "Eres el más trabajador de tus hermanos.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 42, enunciado: "Mi abuelo es tan sabio como un libro.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 43, enunciado: "Es el cuento más fantástico de la biblioteca.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 44, enunciado: "El patio es grande.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 45, enunciado: "La caja está vacía.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 46, enunciado: "Mi abuelo es el más viejo de la familia.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 47, enunciado: "Juan es el más alto de la clase.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 48, enunciado: "La sopa está tan caliente como el café.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 49, enunciado: "El dibujo es menos complejo que el mapa.", opciones: ["Comparativo de Inferioridad", "Positivo", "Comparativo de Igualdad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 50, enunciado: "Un cuento es menos extenso que una novela.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 51, enunciado: "Es la flor más bonita del jardín.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 52, enunciado: "Eres el alumno más atento de la fila.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 53, enunciado: "Mi bici es la más nueva del parque.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 54, enunciado: "La maestra es listísima.", opciones: ["Comparativo de Superioridad", "Superlativo", "Comparativo de Igualdad", "Positivo"], correcta:  1, observaciones: "" },
 { id: 55, enunciado: "El guante es de lana.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 56, enunciado: "La calle es ruidosa.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 57, enunciado: "La clase está limpia.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 58, enunciado: "El estanque es menos agitado que el océano.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 59, enunciado: "El viento es fuerte.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 60, enunciado: "La lámpara es brillante.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 61, enunciado: "La luz es tan blanca como la cal.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 62, enunciado: "El niño es tan fuerte como su padre.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 63, enunciado: "La piedra es pesada.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 64, enunciado: "El robot es tan inteligente como el humano.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 65, enunciado: "La sopa está calentísima.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 66, enunciado: "El cuento es cortísimo.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 67, enunciado: "Mi vaso está menos lleno que el tuyo.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 68, enunciado: "La arena es fina.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 69, enunciado: "La vela es menos luminosa que la bombilla.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 70, enunciado: "La sandía es más grande que la naranja.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 71, enunciado: "La fresa es tan roja como la cereza.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 72, enunciado: "El césped es verde.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 73, enunciado: "Este pastel es el más dulce de la tienda.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 74, enunciado: "El arbusto es menos alto que el pino.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 75, enunciado: "El cielo está despejado.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 76, enunciado: "El sol es brillante.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 77, enunciado: "Juan es tan alto como Pedro.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 78, enunciado: "La fruta es sana.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 79, enunciado: "El tigre es feroz.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 80, enunciado: "El aire es tan puro como la montaña.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 81, enunciado: "El coche es azul.", opciones: ["Positivo", "Comparativo de Superioridad", "Superlativo", "Comparativo de Inferioridad"], correcta:  0, observaciones: "" },
 { id: 82, enunciado: "La película fue divertidísima.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 83, enunciado: "El espacio es grandísimo.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 84, enunciado: "El tesoro es tan valioso como la joya.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 85, enunciado: "El río es larguísimo.", opciones: ["Comparativo de Superioridad", "Superlativo", "Comparativo de Igualdad", "Positivo"], correcta:  1, observaciones: "" },
 { id: 86, enunciado: "El cuento es tan fantástico como el sueño.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 87, enunciado: "La noche es tan oscura como la cueva.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 88, enunciado: "El libro es divertido.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 89, enunciado: "El elefante es enorme.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 90, enunciado: "El trueno es más fuerte que el susurro.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 91, enunciado: "El bosque es oscuro.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 92, enunciado: "La música es alegre.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 93, enunciado: "El fuego es más caliente que el humo.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 94, enunciado: "El payaso es tan divertido como el mago.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 95, enunciado: "El algodón es tan suave como la seda.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 96, enunciado: "El patio está tan limpio como el aula.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 97, enunciado: "El mar es salado.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 98, enunciado: "El león es más fuerte que el ratón.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 99, enunciado: "El té está menos dulce que el refresco.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 100, enunciado: "El examen fue tan fácil como el anterior.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 101, enunciado: "El gato es rapidísimo.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 102, enunciado: "El juguete es moderno.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 103, enunciado: "La nieve es tan fría como el hielo.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 104, enunciado: "Nadar es más divertido que correr.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 105, enunciado: "La tarta es tan dulce como el caramelo.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 106, enunciado: "El mar es tan azul como el cielo.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 107, enunciado: "La flor es fragante.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 108, enunciado: "La tarta estaba buenísima.", opciones: ["Superlativo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 109, enunciado: "El ejercicio es dificilísimo.", opciones: ["Comparativo de Superioridad", "Superlativo", "Comparativo de Igualdad", "Positivo"], correcta:  1, observaciones: "" },
 { id: 110, enunciado: "La nube es blanca.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 111, enunciado: "La joya es valiosísima.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 112, enunciado: "El helado está riquísimo.", opciones: ["Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 113, enunciado: "El lápiz es tan largo como el bolígrafo.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 114, enunciado: "Este lápiz es más largo que aquel.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 115, enunciado: "El bosque es tan espeso como la selva.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 116, enunciado: "Eres el niño más valiente de todos.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 117, enunciado: "El guerrero es tan valiente como el león.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 118, enunciado: "El gato es tan ágil como el conejo.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 119, enunciado: "Mi mochila es nueva.", opciones: ["Positivo", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 120, enunciado: "El invierno es tan triste como la lluvia.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 121, enunciado: "La luna es tan redonda como una pelota.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 122, enunciado: "Mi primo es tan bajo como mi hermana.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 123, enunciado: "El día está nublado.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 124, enunciado: "Mi dibujo es tan bonito como el tuyo.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 125, enunciado: "El agua es menos densa que el aceite.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Positivo", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 126, enunciado: "La bufanda es tan suave como la manta.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 127, enunciado: "Eres el más saltarín de los niños.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 128, enunciado: "El ratón es menos feroz que el lobo.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 129, enunciado: "La luna es menos brillante que el sol.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  2, observaciones: "" },
 { id: 130, enunciado: "La nieve es friísima.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 131, enunciado: "María es la niña más aplicada del colegio.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 132, enunciado: "Esta es la manzana más roja del árbol.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 133, enunciado: "La película es tan larga como el libro.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 134, enunciado: "El examen fue más difícil que el anterior.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 135, enunciado: "Es el juguete más caro de la juguetería.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 136, enunciado: "El estuche es tan pequeño como la caja.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 137, enunciado: "La ardilla es tan rápida como el ratón.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 138, enunciado: "El chocolate es más dulce que el pan.", opciones: ["Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 139, enunciado: "El árbol es alto.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 140, enunciado: "El pájaro es veloz.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 141, enunciado: "La falda es menos larga que el pantalón.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 142, enunciado: "Tu habitación está limpísima.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 143, enunciado: "Es el río más caudaloso de la región.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 144, enunciado: "Mi casa es tan cómoda como la tuya.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 145, enunciado: "La ballena es más enorme que el delfín.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 146, enunciado: "Un segundo es menos largo que un minuto.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 147, enunciado: "El parque es tan grande como la plaza.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 148, enunciado: "Mi padre es más fuerte que mi primo.", opciones: ["Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 149, enunciado: "El viaje fue larguísimo.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 150, enunciado: "Mi cama es comodísima.", opciones: ["Superlativo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 151, enunciado: "El gato es menos ruidoso que el perro.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Positivo", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 152, enunciado: "Mi perro es pequeñísimo.", opciones: ["Superlativo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 153, enunciado: "Eres el mejor amigo del mundo.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 154, enunciado: "Es la película más graciosa que he visto.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 155, enunciado: "El arpa es menos pequeña que la flauta.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 156, enunciado: "El camino es largo.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 157, enunciado: "El lápiz es amarillo.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 158, enunciado: "El fósforo es menos duradero que la linterna.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 159, enunciado: "La bici es menos potente que la moto.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 160, enunciado: "El parque está llenísimo.", opciones: ["Comparativo de Superioridad", "Superlativo", "Comparativo de Igualdad", "Positivo"], correcta:  1, observaciones: "" },
 { id: 161, enunciado: "La voz es tan dulce como la miel.", opciones: ["Comparativo de Superioridad", "Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 162, enunciado: "La mesa es dura.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 163, enunciado: "La bota es más resistente que la sandalia.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 164, enunciado: "El sofá es blando.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 165, enunciado: "La hormiga es menos pesada que el elefante.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  2, observaciones: "" },
 { id: 166, enunciado: "La película es corta.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 167, enunciado: "Es la sopa más rica que hace la abuela.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 168, enunciado: "El helado es dulce.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 169, enunciado: "El invierno es menos soleado que el verano.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 170, enunciado: "Es la noche más oscura del año.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 171, enunciado: "Mi borrador es menos nuevo que el tuyo.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 172, enunciado: "La ventana está abierta.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 173, enunciado: "La bufanda es larga.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 174, enunciado: "Mi padre es altísimo.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 175, enunciado: "El verano es más caluroso que la primavera.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 176, enunciado: "Mi estuche es menos ancho que la mesa.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Positivo", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 177, enunciado: "La naranja es tan ácida como el limón.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 178, enunciado: "El cristal es transparente.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 179, enunciado: "Tu perro es tan juguetón como el mío.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 180, enunciado: "Es el coche más veloz del circuito.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 181, enunciado: "El perro es leal.", opciones: ["Positivo", "Comparativo de Superioridad", "Superlativo", "Comparativo de Inferioridad"], correcta:  0, observaciones: "" },
 { id: 182, enunciado: "El tren es tan rápido como el avión.", opciones: ["Comparativo de Inferioridad", "Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 183, enunciado: "El día es más luminoso que la tarde.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 184, enunciado: "El sueño es tan profundo como el mar.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 185, enunciado: "El triciclo es menos rápido que la bici.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  2, observaciones: "" },
 { id: 186, enunciado: "La radio es tan antigua como la tele.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 187, enunciado: "Eres el más rápido del equipo.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 188, enunciado: "La selva es más húmeda que el desierto.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 189, enunciado: "El avión es más rápido que el coche.", opciones: ["Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 190, enunciado: "El examen es fácil.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 191, enunciado: "La calle es tan ancha como la avenida.", opciones: ["Comparativo de Superioridad", "Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 192, enunciado: "Caminar es menos cansado que saltar.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 193, enunciado: "La manzana es tan verde como la hierba.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 194, enunciado: "El pastel es rico.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 195, enunciado: "Tu bici es tan veloz como la mía.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 196, enunciado: "El diamante es más duro que el cristal.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 197, enunciado: "La sopa está caliente.", opciones: ["Positivo", "Comparativo de Superioridad", "Superlativo", "Comparativo de Inferioridad"], correcta:  0, observaciones: "" },
 { id: 198, enunciado: "El bosque es oscurísimo.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 199, enunciado: "Es el camino más corto a casa.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 200, enunciado: "El jersey es tan cómodo como el pijama.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 201, enunciado: "El actor es tan famoso como el cantante.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 202, enunciado: "Tu dibujo es hermosísimo.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 203, enunciado: "El león es el más feroz de la selva.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 204, enunciado: "Mi perro es más viejo que tu gato.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  2, observaciones: "" },
 { id: 205, enunciado: "El limón es ácido.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 206, enunciado: "El gigante es tan pesado como un camión.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 207, enunciado: "El gigante es fuertísimo.", opciones: ["Superlativo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 208, enunciado: "El zapato es cómodo.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 209, enunciado: "El mar es profundísimo.", opciones: ["Superlativo", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 210, enunciado: "Mi hermano es más alto que yo.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad"], correcta:  3, observaciones: "" },
 { id: 211, enunciado: "El dibujo es bonito.", opciones: ["Comparativo de Inferioridad", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 212, enunciado: "La pintura es tan brillante como el oro.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 213, enunciado: "El papel es blanco.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 214, enunciado: "El examen era facilísimo.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 215, enunciado: "El delfín es tan simpático como el perro.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 216, enunciado: "El pan está tan tierno como el bizcocho.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 217, enunciado: "El reloj es tan preciso como el tuyo.", opciones: ["Comparativo de Superioridad", "Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 218, enunciado: "El oro es más caro que la plata.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 219, enunciado: "La ensalada es tan sana como la fruta.", opciones: ["Positivo", "Comparativo de Igualdad", "Superlativo", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 220, enunciado: "La cabaña es menos grande que el palacio.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Positivo", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 221, enunciado: "El hierro es más pesado que el corcho.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 222, enunciado: "El gato es suave.", opciones: ["Positivo", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  0, observaciones: "" },
 { id: 223, enunciado: "La cama está hecha.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 224, enunciado: "Mi abuela es cariñosísima.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 225, enunciado: "Un lápiz es menos pesado que una piedra.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 226, enunciado: "Mi cuarto es el más ordenado de la casa.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 227, enunciado: "Es el helado más frío de la nevera.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Superlativo"], correcta:  3, observaciones: "" },
 { id: 228, enunciado: "El río es más largo que el arroyo.", opciones: ["Comparativo de Igualdad", "Comparativo de Inferioridad", "Comparativo de Superioridad", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 229, enunciado: "Es la montaña más alta del país.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 230, enunciado: "El coche es tan ruidoso como la moto.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 231, enunciado: "Este es el libro más aburrido de la estantería.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Superlativo", "Positivo"], correcta:  2, observaciones: "" },
 { id: 232, enunciado: "Mi perro es el más juguetón del barrio.", opciones: ["Comparativo de Igualdad", "Superlativo", "Comparativo de Superioridad", "Comparativo de Inferioridad"], correcta:  1, observaciones: "" },
 { id: 233, enunciado: "La puerta es vieja.", opciones: ["Comparativo de Superioridad", "Comparativo de Igualdad", "Positivo", "Superlativo"], correcta:  2, observaciones: "" },
 { id: 234, enunciado: "Mi tía es tan joven como mi madre.", opciones: ["Comparativo de Superioridad", "Positivo", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 235, enunciado: "El espejo está limpio.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 236, enunciado: "La piscina es tan honda como la bañera.", opciones: ["Positivo", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad"], correcta:  3, observaciones: "" },
 { id: 237, enunciado: "Un arbusto tiene menos hojas que un bosque.", opciones: ["Comparativo de Superioridad", "Comparativo de Inferioridad", "Comparativo de Igualdad", "Superlativo"], correcta:  1, observaciones: "" },
 { id: 238, enunciado: "La maestra es paciente.", opciones: ["Comparativo de Igualdad", "Comparativo de Superioridad", "Comparativo de Inferioridad", "Positivo"], correcta:  3, observaciones: "" },
 { id: 239, enunciado: "El coche es rapidísimo.", opciones: ["Superlativo", "Comparativo de Igualdad", "Comparativo de Superioridad", "Positivo"], correcta:  0, observaciones: "" },
 { id: 240, enunciado: "El edificio es tan alto como la torre.", opciones: ["Comparativo de Igualdad", "Positivo", "Comparativo de Inferioridad", "Superlativo"], correcta:  0, observaciones: "" }



];
